// How much the research agrees on each desk bill's effects, and where the numbers come from.
// Client-only (the server engine never reads it), so editing it needs no engine bump or redeploy.
// Covers the 50 bills students see most often; bills not listed simply show no line.
// Grades: S = most studies agree on the direction, M = studies disagree or results depend on design,
// C = little hard evidence or sharp disagreement, so the game's numbers are a judgment call.
export const GRADE = {
  S: 'Strong: most studies agree on the direction',
  M: 'Mixed: studies disagree, or results depend on the details',
  C: 'Contested: little hard evidence, so these numbers are a judgment call',
};
export const EVID = {
  pipeline: ['M', 'PHMSA pipeline incident data; Furchtgott-Roth & Green, Fraser Institute (2013), on pipeline vs. rail spills'],
  antitrust: ['C', 'EU Digital Markets Act (2022); United States v. Google (D.D.C. 2024)'],
  overtime: ['M', 'U.S. Department of Labor, regulatory impact analysis of the 2024 overtime rule'],
  dividendtax: ['M', 'Yagan (2015, American Economic Review), on the 2003 dividend tax cut and investment'],
  farmsub: ['S', 'USDA Economic Research Service, commodity payment data; OECD reviews of New Zealand’s 1984 farm reforms'],
  seasonal: ['M', 'USDA Economic Research Service, H-2A program data; DHS H-2B visa caps'],
  cut10: ['S', 'Ramey (2019, Journal of Economic Perspectives), on fiscal multipliers; CBO'],
  visa: ['S', 'Kerr & Lincoln (2010, Journal of Labor Economics); National Academies, The Economic and Fiscal Consequences of Immigration (2017)'],
  age69: ['S', 'Chetty et al. (2016, JAMA), on life expectancy by income; Social Security Trustees Report'],
  ssp: ['C', 'CBO and Social Security Advisory Board analyses of transition costs; Chile’s pension reforms (2008 onward)'],
  civilserv: ['M', 'OPM Federal Employee Viewpoint Survey; GAO reports on addressing poor performers'],
  permit: ['M', 'Brooks & Liscow (2023, AEJ: Applied), on rising US infrastructure costs'],
  aidcut: ['M', 'Congressional Research Service, foreign aid overview; KFF polling on budget perceptions'],
  everify: ['M', 'Bohn, Lofstrom & Raphael (2014, Review of Economics and Statistics), on Arizona’s E-Verify mandate'],
  jonesact: ['S', 'U.S. International Trade Commission studies; GAO (2013), on Puerto Rico shipping'],
  balbud: ['M', 'CBO; GAO and CRS histories of the Gramm-Rudman-Hollings targets'],
  land: ['M', 'Congressional Research Service, Federal Land Ownership: Overview and Data (2020)'],
  regs: ['C', 'OMB annual reports to Congress on the benefits and costs of federal regulations'],
  zone: ['S', 'Hsieh & Moretti (2019, AEJ: Macroeconomics); Greenaway-McGrevy & Phillips (2023, Journal of Urban Economics), on Auckland'],
  vouch: ['C', 'Abdulkadiroğlu, Pathak & Walters (2018, AEJ: Applied), on Louisiana; federal evaluations of the DC Opportunity Scholarship Program'],
  pacpact: ['M', 'Petri & Plummer, Peterson Institute for International Economics (2019), CPTPP estimates'],
  meritpay: ['M', 'Springer et al. (2010), the Nashville POINT experiment; Fryer (2013, Journal of Labor Economics), on New York City'],
  carbon: ['S', 'Economists’ Statement on Carbon Dividends (2019); CBO distributional analyses of carbon pricing'],
  dodd: ['C', 'Federal Reserve Board, Review of the Supervision and Regulation of Silicon Valley Bank (2023)'],
  trade: ['S', 'Autor, Dorn & Hanson (2013, American Economic Review), the “China shock”; surveys of economists on free trade'],
  crypto: ['M', 'The 2025 federal stablecoin law (GENIUS Act); FTX bankruptcy proceedings'],
  ipo: ['M', 'Doidge, Karolyi & Stulz (2017, Journal of Financial Economics), “The U.S. listing gap”'],
  ssfix: ['S', 'Social Security Trustees Report; the 1983 Greenspan Commission reforms'],
  scopeprac: ['S', 'Traczynski & Udalova (2018, Journal of Health Economics); National Academies, The Future of Nursing'],
  medmal: ['M', 'Kessler & McClellan (1996, Quarterly Journal of Economics); CBO (2009) on tort reform savings'],
  police: ['S', 'Chalfin & McCrary (2018, Review of Economics and Statistics), “Are US Cities Underpoliced?”'],
  certneed: ['M', 'FTC & DOJ, Improving Health Care: A Dose of Competition (2004); state-level studies of repeal'],
  cfpb: ['C', 'CFPB enforcement and relief data; CFPB v. Community Financial Services Association (2024)'],
  drugimport: ['M', 'RAND international prescription drug price comparisons; CBO estimates of importation savings'],
  cvi: ['M', 'Butts et al. (2015, Annual Review of Public Health), on Cure Violence; Braga, Weisburd & Turchan (2018), focused deterrence meta-analysis'],
  ubi: ['M', 'Vivalt et al. (2024, NBER), the OpenResearch unconditional cash study'],
  hsa: ['S', 'The RAND Health Insurance Experiment; Brot-Goldberg et al. (2017, Quarterly Journal of Economics)'],
  broadband: ['M', 'GAO reviews of federal broadband programs; NTIA BEAD program records'],
  lic: ['S', 'Kleiner & Krueger (2013, Journal of Labor Economics); White House, Occupational Licensing: A Framework for Policymakers (2015)'],
  buyamerica: ['M', 'GAO and Congressional Research Service reviews of Buy American rules'],
  transitfund: ['S', 'Ewing & Cervero (2010, Journal of the American Planning Association), meta-analysis of travel and the built environment'],
  aireg: ['C', 'EU Artificial Intelligence Act (2024); US executive orders and voluntary company commitments'],
  hsr: ['M', 'NYU Transit Costs Project (2023); California High-Speed Rail Authority business plans'],
  wildfire: ['S', 'Kolden (2019, Fire), on prescribed fire in the western US; US Forest Service wildfire strategy'],
  ctc: ['M', 'Census Bureau Supplemental Poverty Measure (2021–2022); studies disagree on effects on parents’ work'],
  cafe: ['S', 'Jacobsen (2013, AEJ: Economic Policy); Anderson & Sallee (2016, Annual Review of Resource Economics)'],
  taa: ['M', 'Mathematica Policy Research TAA evaluation (2012); Hyman (2018), “Can Displaced Labor Be Retrained?”'],
  infra: ['M', 'Ramey (2020, NBER), on the macroeconomic effects of infrastructure investment; CBO'],
  wetlands: ['C', 'Sackett v. EPA (2023); EPA and Army Corps economic analyses of the waters rule'],
  secretballot: ['C', 'National Labor Relations Board election data'],
};
export const evidenceFor = (id) => { const e = EVID[id]; return e ? { grade: GRADE[e[0]], src: e[1] } : null; };
