// Written summaries of a finished game, generated by rules (no AI, no network) from the server-computed decision digest.
// buildSummary: one student. buildClassSummary: the whole class, for the teacher.
const START = { g: 0, j: 4.3, i: 3.0, d: 5.8, a: 48, u: 15 };
const KEYS = ['g', 'j', 'i', 'd', 'a', 'u'];
const NAME = { g: 'economic growth', j: 'unemployment', i: 'inflation', d: 'the deficit', a: 'approval', u: 'unrest' };
const SCALE = { g: 1.5, j: 1, i: 1, d: 1.5, a: 10, u: 10 };
const r1 = (v) => Math.round(v * 10) / 10;
const list = (a) => (a.length <= 1 ? a.join('') : a.slice(0, -1).join(', ') + ' and ' + a[a.length - 1]);
const q = (s) => '“' + s + '”';
const plural = (n, w) => n + ' ' + w + (n === 1 ? '' : 's');

// how much better (+) or worse (-) a meter ended than where it began, in "typical swing" units
function change(k, now) {
  const d = k === 'g' || k === 'a' ? now - START[k] : k === 'i' ? Math.abs(START.i - 2) - Math.abs(now - 2) : START[k] - now;
  return d / SCALE[k];
}
const fmt = { g: (v) => (v >= 0 ? '+' : '−') + Math.abs(v).toFixed(1) + '%', j: (v) => v.toFixed(1) + '%', i: (v) => v.toFixed(1) + '%', d: (v) => v.toFixed(1) + '% of GDP', a: (v) => Math.round(v) + '%', u: (v) => String(Math.round(v)) };
const START_TXT = { g: '0.0%', j: '4.3%', i: '3.0%', d: '5.8% of GDP', a: '48%', u: '15' };

function polImpact(p) {
  // expected effect of a policy on the country, positive = better. f is in meter order [g, j, i, d, a, u].
  let s = 0; KEYS.forEach((k, i) => { const f = p.f[i] || 0; s += (k === 'g' || k === 'a' ? f : -f) / SCALE[k]; });
  return s;
}
function lean(nd) {
  return nd < 35 ? 'a heavily government-planned economy' : nd < 45 ? 'a somewhat planned economy' : nd <= 55 ? 'a mixed economy' : nd <= 65 ? 'a somewhat market-driven economy' : 'a strongly free-market economy';
}

// eng: Engine (for the data tables). d: digest. meta: { score, cons, lib, name, status }
export function buildSummary(eng, d, meta) {
  const D = eng.data(); const m = meta || {};
  const pol = (id) => D.POL.find((x) => x.id === id) || D.XA.find((x) => x.id === id);
  const days = d.days;
  const end = d.ser && d.ser.length ? d.ser[d.ser.length - 1] : null;
  const fin = end ? { g: end[1], j: end[2], i: end[3], d: end[4], a: end[5], u: end[6] } : null;
  const out = { headline: '', stats: [], paras: [], helped: null, hurt: null, questions: [] };

  const signed = d.signed.filter((id) => pol(id)); const nSigned = signed.length, nVeto = d.nv || 0;
  const decided = nSigned + nVeto;
  const how = d.over ? (d.ok === 'impeach' ? 'You were removed from office by the Senate' : d.ok === 'coup' ? 'You were overthrown' : d.ok === 'fled' ? 'You fled the country' : 'Your term ended early')
    : 'You finished the full ' + days + '-day term';
  out.headline = how + (m.score != null ? ' with a score of ' + m.score + (m.cons ? ' (conservative grade ' + m.cons + ', liberal grade ' + m.lib + ')' : '') : '') + '.';

  // --- 1. overview of choices
  const style = decided === 0 ? 'You did not sign or veto a single memo.' : 'You decided on ' + plural(decided, 'memo') + ': you signed ' + nSigned + ' and vetoed ' + nVeto + '.';
  const leanTxt = ' Taken together your policies pushed the country toward ' + lean(d.nd) + '.';
  const xa = d.xa.filter((id) => pol(id));
  const dark = xa.filter((id) => D.XA.find((x) => x.id === id && x.cat === 'power'));
  const xaTxt = xa.length ? ' You used ' + plural(xa.length, 'executive action') + ' (' + list(xa.map((id) => q(pol(id).t))) + ')' + (dark.length ? ', including ' + plural(dark.length, 'power play') + ' that carry scandal risk' : '') + '.' : ' You never used an executive action.';
  out.paras.push(style + leanTxt + xaTxt);

  // --- 2. how the country changed
  if (fin) {
    const ranked = KEYS.map((k) => ({ k, c: change(k, fin[k]) })).sort((a, b) => b.c - a.c);
    const best = ranked.filter((x) => x.c > 0.15).slice(0, 2), worst = ranked.filter((x) => x.c < -0.15).reverse().slice(0, 2);
    const mv = (x) => NAME[x.k] + ' (' + START_TXT[x.k] + ' to ' + fmt[x.k](fin[x.k]) + ')';
    let t = 'Where the country improved: ' + (best.length ? list(best.map(mv)) : 'nothing improved by much') + '. ';
    t += 'Where it got worse: ' + (worst.length ? list(worst.map(mv)) : 'nothing got much worse') + '.';
    t += ' These are the numbers at the end of your last day; your score also counts where they were headed.';
    out.paras.push(t);
    out.stats = KEYS.map((k) => ({ k: NAME[k][0].toUpperCase() + NAME[k].slice(1), start: START_TXT[k], end: fmt[k](fin[k]), good: change(k, fin[k]) > 0.05, bad: change(k, fin[k]) < -0.05 }));
  }

  // --- 3. the decisions that mattered most
  const allActs = signed.concat(xa).filter((id) => !(d.repealed || []).includes(id)).map((id) => ({ id, p: pol(id), s: polImpact(pol(id)) })).filter((x) => x.p && x.p.f);
  allActs.sort((a, b) => b.s - a.s);
  const top = allActs[0], bot = allActs[allActs.length - 1];
  if (top && top.s > 0.4) {
    out.helped = { title: top.p.t, tradeoff: top.p.con };
    out.paras.push('The decision most likely to have helped: ' + q(top.p.t) + '. Even a good result has a cost. Critics point out: ' + top.p.con.replace(/^./, (c) => c.toLowerCase()));
  }
  if (bot && bot !== top && bot.s < -0.4) {
    out.hurt = { title: bot.p.t, defense: bot.p.pro };
    out.paras.push('The decision most likely to have hurt: ' + q(bot.p.t) + '. Its supporters would answer: ' + bot.p.pro.replace(/^./, (c) => c.toLowerCase()));
  }
  if (!out.helped && !out.hurt && nSigned + xa.length) out.paras.push('None of your choices moved the country sharply in one direction. Policies often cancel each other out, which is why many real governments seem to change things slowly.');
  if (d.repealed && d.repealed.length) out.paras.push('You repealed ' + list(d.repealed.filter((id) => pol(id)).map((id) => q(pol(id).t))) + ', which shows that laws can be undone when the results disappoint.');
  if (d.moot && d.moot.length) out.paras.push('Your executive actions settled ' + plural(d.moot.length, 'issue') + ' that Congress would otherwise have voted on. That is a real feature of executive power: it can make a legislative debate unnecessary.');

  // --- 4. events and crises
  const evs = (d.ev || []).map((e) => { const [day, id] = e.split(':'); const E = D.EV[id]; return E ? { day: +day, t: E.title.replace(' {st}', '').replace('{st}', '').trim() } : null; }).filter(Boolean);
  const fus = (d.fu || []).map((f) => { const [, id, sk, sid] = f.split(':'); return pol(id) && pol(sid) ? { c: pol(id).t, sk: sk, p: pol(sid).t } : null; }).filter(Boolean);
  if (fus.length) {
    const ex = fus.slice(0, 3).map((o) => q(o.c) + ' came up because ' + (o.sk === 'v' ? 'you vetoed ' : o.sk === 'x' ? 'of your executive action ' : 'you signed ') + q(o.p));
    out.paras.push('Your choices shaped what landed on your desk next: ' + plural(fus.length, 'follow-up bill') + ' appeared as a result. For example, ' + list(ex) + '. In real government, one law often creates the need for the next.');
  }
  const crs = (d.cr || []).map((c) => { const [day, fac, pid] = c.split(':'); const F = D.FAC[fac]; return F ? { day: +day, t: F.name, p: pid && pol(pid) ? pol(pid).t : '' } : null; }).filter(Boolean);
  if (evs.length || crs.length) {
    let t = '';
    if (evs.length) t += 'Along the way the country faced: ' + evs.slice(0, 4).map((e) => e.t + ' (day ' + e.day + ')').join('; ') + '. ';
    if (crs.length) t += 'Unrest broke out ' + plural(crs.length, 'time') + (crs.some((c) => c.p) ? ', for example after ' + q(crs.find((c) => c.p).p) + ' angered a group' : '') + '. This is how a policy that looks good on paper can still create a backlash.';
    out.paras.push(t.trim());
  }

  // --- 5. standing
  if (d.lvl !== 1) {
    let t = 'At the end your scandal level was ' + Math.round(d.scand) + ' out of 100 and Congress’s support was ' + Math.round(d.cong) + '.';
    if (d.trials) t += ' You faced an impeachment trial' + (d.surv ? ' and survived it.' : '.');
    if (d.rev) t += ' A revolt reached the capital.';
    out.paras.push(t);
  }

  // --- reflection questions, picked from what actually happened
  const Q = {
    g: 'Which of your policies slowed down growth, and would you accept that trade-off?',
    j: 'Which of your choices made it harder or more expensive for employers to hire?',
    i: 'What happened to prices after your biggest spending or wage decisions, and why?',
    d: 'If you had to close the deficit, whose taxes or benefits would you change?',
    a: 'Which decision do you think people liked the least? Would you make it again?',
    u: 'What made people angry, and could you have seen it coming?',
  };
  if (fin) {
    const w = KEYS.map((k) => ({ k, c: change(k, fin[k]) })).sort((a, b) => a.c - b.c)[0];
    out.questions.push(Q[w.k]);
  }
  if (dark.length) out.questions.push('Is it ever acceptable for a President to act alone or bend the rules? Where would you draw the line?');
  else if (xa.length) out.questions.push('Executive actions skip Congress. When is that a strength and when is it a risk?');
  if (nVeto > nSigned) out.questions.push('You vetoed most memos. Did you decide based on the evidence, or on your own beliefs?');
  else if (nVeto === 0 && nSigned > 3) out.questions.push('You signed everything. What would a good reason to veto a popular policy look like?');
  out.questions.push('Which real-world evidence changed your mind about a policy, and which did you ignore?');
  out.questions = out.questions.slice(0, 3);
  return out;
}

// rows: [{ display_name, score, completion_status, needle, digest }] (finished students). Returns teacher-facing class insights.
export function buildClassSummary(eng, rows, days) {
  const D = eng.data();
  const pol = (id) => D.POL.find((x) => x.id === id) || D.XA.find((x) => x.id === id);
  const R = rows.filter((r) => r.digest);
  const n = R.length;
  const out = { n, paras: [], tables: [], questions: [] };
  if (!n) { out.paras.push('No finished students yet. The class summary appears when the first results arrive.'); return out; }
  const scores = R.map((r) => r.score).sort((a, b) => a - b);
  const avg = Math.round(scores.reduce((a, b) => a + b, 0) / n), med = scores[Math.floor(n / 2)];
  const removed = R.filter((r) => r.completion_status === 'removed').length;
  out.paras.push(plural(n, 'student') + ' finished the ' + days + '-day simulation. Scores ranged from ' + scores[0] + ' to ' + scores[n - 1] + ' (average ' + avg + ', median ' + med + ').' + (removed ? ' ' + plural(removed, 'student') + ' ended up removed, overthrown, or fleeing before the term ended.' : ' Everyone finished their term.'));

  // sign / veto tallies per policy (only memos that were actually decided)
  const sign = {}, veto = {}, xaUse = {};
  R.forEach((r) => { r.digest.signed.forEach((id) => { sign[id] = (sign[id] || 0) + 1; }); (r.digest.vetoed || []).forEach((id) => { veto[id] = (veto[id] || 0) + 1; }); r.digest.xa.forEach((id) => { xaUse[id] = (xaUse[id] || 0) + 1; }); });
  const ids = Object.keys(Object.assign({}, sign, veto)).filter((id) => pol(id));
  const rowsP = ids.map((id) => ({ id, s: sign[id] || 0, v: veto[id] || 0 })).map((o) => Object.assign(o, { seen: o.s + o.v, pct: Math.round(100 * o.s / Math.max(1, o.s + o.v)) })).filter((o) => o.seen >= Math.min(3, n));
  const split = rowsP.filter((o) => o.pct >= 30 && o.pct <= 70).sort((a, b) => b.seen - a.seen).slice(0, 4);
  if (split.length) out.paras.push('Most divisive decisions (the class was split): ' + list(split.map((o) => q(pol(o.id).t) + ' (' + o.pct + '% signed)')) + '. These are good starting points for a discussion.');
  const agree = rowsP.filter((o) => o.pct >= 90 || o.pct <= 10).sort((a, b) => b.seen - a.seen).slice(0, 3);
  if (agree.length) out.paras.push('Near-unanimous: ' + list(agree.map((o) => q(pol(o.id).t) + ' (' + (o.pct >= 90 ? 'signed' : 'vetoed') + ' by ' + Math.max(o.pct, 100 - o.pct) + '%)')) + '.');
  const topX = Object.entries(xaUse).sort((a, b) => b[1] - a[1]).filter(([id]) => pol(id)).slice(0, 3);
  if (topX.length) out.paras.push('Most-used executive actions: ' + list(topX.map(([id, c]) => q(pol(id).t) + ' (' + c + ')')) + '.');
  const dark = R.filter((r) => r.digest.xa.some((id) => D.XA.find((x) => x.id === id && x.cat === 'power'))).length;
  if (dark) out.paras.push(plural(dark, 'student') + ' used at least one power play (a high-scandal executive action).');

  // do the choices connect to the outcomes?
  const lean = R.filter((r) => r.needle != null);
  if (lean.length >= 4) {
    const planned = lean.filter((r) => r.needle < 45), market = lean.filter((r) => r.needle > 55);
    const av = (a, k) => Math.round(a.reduce((s, r) => s + k(r), 0) / a.length);
    if (planned.length >= 2 && market.length >= 2) out.paras.push('Students whose policies leaned planned (' + planned.length + ') averaged a score of ' + av(planned, (r) => r.score) + ', compared with ' + av(market, (r) => r.score) + ' for students who leaned market (' + market.length + '). With a class this size treat that as a conversation starter, not a conclusion.');
  }
  // insight per divisive policy
  split.slice(0, 2).forEach((o) => {
    const a = R.filter((r) => r.digest.signed.includes(o.id)), b = R.filter((r) => !r.digest.signed.includes(o.id));
    if (a.length >= 2 && b.length >= 2) {
      const av = (arr, k) => arr.reduce((s, r) => s + k(r), 0) / arr.length;
      out.paras.push('Students who signed ' + q(pol(o.id).t) + ' (' + a.length + ') ended with average approval ' + Math.round(av(a, (r) => r.digest.ser[r.digest.ser.length - 1][5])) + '% and unemployment ' + r1(av(a, (r) => r.digest.ser[r.digest.ser.length - 1][2])) + '%; those who did not (' + b.length + ') ended with ' + Math.round(av(b, (r) => r.digest.ser[r.digest.ser.length - 1][5])) + '% and ' + r1(av(b, (r) => r.digest.ser[r.digest.ser.length - 1][2])) + '%.');
    }
  });
  // shared events (same seed => same events for everyone)
  const first = R[0].digest;
  const evs = (first.ev || []).map((e) => { const [day, id] = e.split(':'); const E = D.EV[id]; return E ? E.title.replace(' {st}', '').replace('{st}', '').trim() + ' (day ' + day + ')' : null; }).filter(Boolean);
  if (evs.length) out.paras.push('Everyone faced the same random events, so differences in outcomes come from decisions. The events were: ' + evs.slice(0, 6).join('; ') + '.');
  const crCount = {}; R.forEach((r) => (r.digest.cr || []).forEach((c) => { const f = c.split(':')[1]; crCount[f] = (crCount[f] || 0) + 1; }));
  const topCr = Object.entries(crCount).sort((a, b) => b[1] - a[1])[0];
  if (topCr && D.FAC[topCr[0]]) out.paras.push('Most common unrest: ' + D.FAC[topCr[0]].name.toLowerCase() + ' (' + topCr[1] + ' times across the class). Ask students which policies set it off.');
  out.questions = [
    'Which decision split the class the most, and what evidence could settle the argument?',
    'Did the highest scorers make the same choices, or did different strategies succeed?',
    'Which policy had the biggest trade-off between helping one group and costing another?',
  ];
  return out;
}
