import { P } from './p.js';
export const ETM = [
// ------------------------------------------------------------------ ENERGY
P('bordercarbon', 'Energy', -1, [-0.1, 0, 0.1, -0.2, 1, 0], 0.5, ['business', 0.15], ['OH', 'PA', 'IN', 'WV'], 1,
  'Add a border carbon fee on imports from countries without a carbon price',
  'Your carbon tax made American steel pay for its smoke. Now imported steel pays too, so factories do not simply move abroad.',
  'Pennsyl-vanity steelworkers cheer a tariff that comes with a climate science lecture.',
  ['Border Carbon Fee Stops Polluters From Dodging the Climate Bill', 'New Import Fee Is a Tariff in a Green Costume, Trading Partners Warn'],
  'The EU began phasing in its Carbon Border Adjustment Mechanism in 2023, starting with reporting before charging fees. Measuring the carbon in imported goods is hard, and trading partners have called such fees disguised tariffs.',
  'Stops carbon leakage: firms cannot dodge the tax by moving production abroad.', 'Hard to measure, raises import prices, and invites retaliation against US exports.',
  'A carbon tax makes polluting more expensive at home. Without a matching fee at the border, factories could move to countries with no carbon tax and ship the same goods back. This fee charges imports for the carbon released in making them. It protects US factories and the climate goal, but it raises prices and other countries may hit back with fees of their own.',
  { req: ['carbon', '!freetrade'], slot: ['bordercarb'] }),
P('climateclub', 'Energy', 1, [0.1, 0, 0, 0.1, 1, 0], 0.5, null, ['MI', 'WA', 'OH'], 1,
  'Exempt allies with their own carbon prices from the border carbon fee',
  'Countries that already tax carbon at home get waved through. Everyone else is invited to join the club.',
  'Club membership opens: the dress code is a carbon price, and the bouncer works at customs.',
  ['Climate Club Rewards Allies Who Price Pollution', 'Climate Club Hands Trade Policy to Foreign Governments, Critics Say'],
  'Economist William Nordhaus proposed a climate club in which countries with carbon prices trade freely and charge outsiders a fee; the EU’s border fee similarly credits carbon prices already paid abroad.',
  'Rewards partners who cut emissions and keeps trade with allies open.', 'Gives up some revenue and depends on trusting other countries’ carbon rules.',
  'After you added a border fee on carbon, some allies point out that they already tax carbon themselves. Charging them twice seems unfair, so this bill lets their goods in without the fee. It keeps friendly trade flowing and gives other countries a reason to price carbon too, but the US collects less money and must trust foreign rules.',
  { req: ['bordercarbon'], dl: 2 }),
P('cleanstd', 'Energy', -1, [-0.2, 0, 0.2, 0, 1, 1], 0.6, ['energy', 0.4], ['WV', 'WY', 'KY', 'ND'], -3,
  'Require utilities to get 80% of their power from clean sources by 2035',
  'Instead of a price on carbon, a rule: utilities must buy more clean power each year, from any mix of wind, solar, nuclear or hydro.',
  'Wyo-Mingle coal country asks whether a wind turbine counts as a coal mine with better posture.',
  ['Clean Power Standard Puts the Grid on a Deadline', 'Power Mandate Will Raise Electric Bills, Utilities Warn'],
  'About 30 states have renewable or clean electricity standards. Economists generally find standards cost more per ton of carbon cut than a carbon price, but they have been easier to pass politically.',
  'A clear target that utilities can plan around, with no new tax.', 'Costs more per ton of carbon cut than a carbon price, and bills may rise.',
  'Power plants are a big source of the gases that warm the planet. This rule says utilities must get a growing share of electricity from clean sources like wind, solar, nuclear and hydro. It is an alternative to a carbon tax: no new tax, just a requirement. Critics say it is a pricier way to cut pollution, and coal regions would lose jobs.',
  { slot: ['carbon'] }),
P('gasbridge', 'Energy', -2, [0.1, -0.1, 0, 0.4, 2, -1], 0.5, null, ['TX', 'PA', 'MI', 'ND', 'NM', 'OH'], 2,
  'Fund a transition bridge for oil, gas and auto workers',
  'Your ban is reshaping whole towns. This pays wages, pensions and retraining for workers whose rigs, refineries and engine plants are closing.',
  'Ohi-NO auto workers are promised a bridge. The union asks how long the bridge is, and who is paving it.',
  ['Bridge Fund Promises No Worker Left Behind in the Energy Shift', 'Taxpayers Asked to Pay for the Damage Done by the Ban'],
  'Studies of past plant and mine closures find laid-off workers often earn less for many years afterward; Germany spent heavily to wind down hard-coal mining gradually, with early retirement and retraining.',
  'Treats displaced workers fairly and eases fierce local opposition.', 'Retraining programs have a mixed record, and the bill adds to the deficit.',
  'A ban on fracking or on new gas cars means some oil fields, refineries and engine plants will close. This bill gives affected workers extra pay while they search for jobs, protects their pensions and pays for training. It softens a hard blow for whole towns, but it costs money and job-training programs do not always lead to good new jobs.',
  { req: [['gasban', 'frack']] }),
P('wellplug', 'Environment', -1, [0.1, -0.1, 0, 0.1, 1, 0], 0.5, null, ['PA', 'OH', 'WV', 'TX'], 1,
  'Hire laid-off drillers to plug abandoned oil and gas wells',
  'Many old wells leak methane with no owner left to pay. The workers who know wells best get the job of closing them.',
  'Pennsyl-vanity finds a well from 1890. It is still leaking, and it is still not paying rent.',
  ['Laid-Off Drillers Get Paid to Clean Up Leaking Wells', 'Another Federal Jobs Program, This Time With Cement'],
  'Agencies count well over 100,000 documented orphaned oil and gas wells, and estimates of undocumented ones run far higher; the 2021 infrastructure law set aside about $4.7 billion to plug them.',
  'Cuts methane and water pollution using skills displaced workers already have.', 'Costs money and is a short-lived source of jobs once the wells are plugged.',
  'An orphaned well is an old oil or gas well whose owner went out of business without sealing it. Many leak methane, a powerful warming gas, and some pollute water. This bill pays workers covered by your transition bridge to plug them. It cleans up pollution and uses real skills, but the work ends when the wells are done.',
  { req: ['gasbridge'], dl: 2 }),
P('pipeline', 'Energy', 2, [0.2, -0.1, -0.1, 0, 0, 1], 0.6, ['urban', 0.2], ['ND', 'TX', 'OK', 'MT'], 2,
  'Set firm deadlines for approving new oil and gas pipelines',
  'Pipelines get a firm deadline for federal review. Oil that now rides in trains and trucks may move underground instead.',
  'Dakota Dakota oil finally gets a ride that is not a train. The train is mildly offended.',
  ['Pipeline Rush Locks In Decades of Fossil Fuel Use', 'Pipeline Bill Cuts Red Tape and Energy Costs'],
  'Some studies find pipelines have fewer spills per barrel moved than rail or trucks, though pipeline spills can be large; projects such as Keystone XL were stalled for years by permits and lawsuits.',
  'Cheaper, safer transport for fuel and more energy jobs.', 'Locks in fossil fuel use and puts land and water at risk from spills.',
  'Pipelines carry oil and natural gas across the country. Getting one approved can take years of reviews and court fights. This bill sets short deadlines for federal decisions. It could lower energy prices and replace riskier rail shipments, but environmental groups and some landowners worry about spills and about building fossil fuel equipment that will run for decades.',
  { req: ['!frack'] }),
P('gridfund', 'Energy', -1, [0.2, -0.1, -0.1, 0.4, 1, 0], 0.6, null, ['TX', 'CA', 'KS'], 1,
  'Fund long-distance power lines to modernize the electric grid',
  'The wind is in Kansas and the people are in Chicago. A federal fund helps build the wires in between.',
  'Kansastic wind farms finally get a long-distance calling plan.',
  ['Grid Upgrade Brings Cheap Clean Power to Cities', 'Federal Grid Fund Spends Billions on Wires Nobody Wants Nearby'],
  'Government and academic studies find the US needs to greatly expand long-distance transmission; such lines often take a decade or more to approve, and the 2021 Texas blackouts exposed the risk of a grid with few links to its neighbors.',
  'Moves cheap power where it is needed and makes blackouts less likely.', 'Costly, and federal money does not solve local fights over where lines go.',
  'The electric grid is the web of wires that carries power from plants to homes. The best places for wind and solar are often far from big cities, and building long power lines is slow and expensive. This fund helps pay for them. It can lower bills and prevent blackouts, but it costs money and neighbors often fight new lines.'),
P('solarcredit', 'Energy', -1, [0.2, -0.1, 0, 0.5, 1, 0], 0.6, ['energy', 0.15], ['AZ', 'NV', 'CA', 'TX'], 2,
  'Expand tax credits for solar, wind and batteries',
  'Build a solar farm or put panels on your roof, and the tax code chips in a larger share.',
  'Arid-zona roofs go solar. The sun says it has been waiting for years.',
  ['Bigger Clean Energy Credits Speed the Solar Boom', 'Solar Credits Hand Billions to Developers Who Would Build Anyway'],
  'Federal tax credits for solar and wind have been extended many times since the mid-2000s; studies find they increased building, though estimates of the cost per ton of carbon avoided vary widely.',
  'Speeds the build-out of cheap clean power and factory jobs.', 'Costly, and part of the money goes to projects that would have been built anyway.',
  'A tax credit cuts the taxes a company or family owes when it does something the government wants to encourage. This bill makes the credits for solar panels, wind farms and big batteries larger. More clean power gets built, faster. But the credits cost the Treasury money, and some of it rewards projects that would have happened without help.',
  { slot: ['cleancredit'], sys: ['deduct'] }),
P('nukesub', 'Energy', -1, [0.2, -0.1, 0, 0.3, 0, 0], 0.6, null, ['GA', 'TN', 'WY', 'ID'], 2,
  'Offer loan guarantees and subsidies for new nuclear reactors',
  'The first few new reactors are always the priciest. Washington offers to share that risk so the tenth one is cheaper.',
  'Wyo-Mingle trades a coal plant for a small reactor. The cows have questions.',
  ['Nuclear Aid Bets Taxpayer Money on Reactors That Run Late', 'Nuclear Comeback Promises Clean Power Around the Clock'],
  'Georgia’s Vogtle Units 3 and 4, the first new US reactors in decades, came online in 2023 and 2024, years late and far over budget; supporters say costs fall as builders gain experience.',
  'Reliable, carbon-free power that runs day and night.', 'Taxpayers carry the risk of the delays and overruns that plagued past projects.',
  'Nuclear power plants make electricity without carbon pollution and run around the clock. But recent US reactors took years longer and cost much more than planned, so few companies want to build them. This bill has the government guarantee loans and provide subsidies to cut that risk. If it works, power becomes cleaner; if projects stumble, taxpayers share the losses.'),
P('gasholiday', 'Energy', 1, [0.1, 0, -0.1, 0.1, 2, 0], 0.4, null, ['TX', 'GA', 'FL', 'OH'], 2,
  'Suspend the federal gas tax for the summer',
  'After the fight over capping gas prices, a smaller idea: skip the 18.4-cent federal tax for three months.',
  'Georgia-ish drivers save 18 cents a gallon. Some gas stations save a few of those cents too.',
  ['Gas Tax Holiday Gives Drivers a Little Summer Relief', 'Gas Tax Holiday Drains the Highway Fund for Pennies at the Pump'],
  'The federal gas tax is 18.4 cents a gallon. Studies of state gas tax holidays generally find that most, but not all, of the cut reaches drivers, and the lost money comes out of the highway trust fund.',
  'Quick, simple relief for drivers when prices are high.', 'Saves each driver little, part goes to sellers, and roads lose funding.',
  'Every gallon of gas includes an 18.4-cent federal tax that pays for highways. This bill pauses that tax for three months. Drivers may save a little at the pump, though gas stations can keep part of the cut. Meanwhile the highway fund loses money, and cheaper gas can raise demand, which keeps prices from falling as much.',
  { req: [['gascap', '~gascap']], slot: ['gastax'] }),
P('spr', 'Energy', 0, [0.1, 0, -0.1, -0.1, 2, 0], 0.4, null, ['TX', 'LA', 'CA'], 1,
  'Release oil from the Strategic Petroleum Reserve',
  'You refused to cap gas prices. Your energy secretary suggests a market-friendly option: sell some of the emergency oil stash.',
  'Looseiana salt caverns open the taps. The oil is old, but it is still on the job.',
  ['Oil Release Brings Fast Relief to Families at the Pump', 'Emergency Oil Reserve Raided for a Political Price Dip'],
  'The reserve stores crude oil in salt caverns in Texas and Louisiana. The US sold roughly 180 million barrels in 2022; estimates of how much that lowered gas prices varied, generally from cents to tens of cents a gallon.',
  'Adds supply quickly without price controls or shortages.', 'Shrinks the cushion saved for real emergencies like wars or hurricanes.',
  'The Strategic Petroleum Reserve is a giant emergency supply of crude oil stored underground. Selling some adds oil to the market, which can lower gas prices a little without the shortages that price caps cause. The catch: oil sold now is not there for a real emergency, like a war or a hurricane that knocks out refineries.',
  { req: ['~gascap'] }),
P('sprrefill', 'Energy', 0, [0, 0, 0.1, 0.2, 0, 0], 0.4, null, ['TX', 'LA'], 1,
  'Buy oil back to refill the emergency reserve when prices fall',
  'You sold reserve oil when prices were high. This buys it back when prices dip, the plan that sounds like plain good sense: buy low.',
  'Texass oil traders discover a new customer: Uncle Sam, who would like to buy low.',
  ['Reserve Refill Restores the Nation’s Energy Safety Net', 'Government Now Playing the Oil Market With Taxpayer Cash'],
  'After the 2022 sales, the Energy Department bought oil back gradually at lower average prices than it had sold at; refilling takes years because the caverns can only take in oil slowly.',
  'Restores emergency supply, ideally buying low after selling high.', 'Costs money and can nudge prices up while the government is buying.',
  'After you sold oil from the emergency reserve, it now holds less. This bill buys oil back when prices fall. If timed well, the government sells high, buys low, and is ready for the next crisis. But buying costs money, and the extra demand can push prices up a little.',
  { req: ['spr'], dl: 3 }),
// ------------------------------------------------------------------ ENVIRONMENT
P('waterinfra', 'Environment', -1, [0.1, -0.1, 0, 0.3, 2, -1], 0.6, null, ['MI', 'IL', 'OH', 'NJ'], 2,
  'Replace every lead water pipe in the country within ten years',
  'Millions of homes still get their water through lead pipes. This pays cities to dig them up.',
  'Michi-gone digs up its lead pipes. The plumbers are booked through 2035.',
  ['Lead Pipe Replacement Protects Kids From Poisoned Water', 'Lead Pipe Mandate Leaves Cities With Potholes and Paperwork'],
  'EPA estimates roughly nine million lead pipes still connect homes to water mains; lead harms children’s brain development even at low levels, as the crisis in Flint, Michigan showed.',
  'Protects children from a poison with no known safe level.', 'Expensive, disruptive digging, and many pipes are hard even to locate.',
  'Some older homes still get tap water through pipes made of lead, a metal that can harm children’s brains. This bill pays cities to find and replace all of them within ten years. It protects health, especially for kids, but it is costly and messy, since crews have to dig up streets and yards to reach each pipe.'),
P('wetlands', 'Environment', -1, [-0.1, 0, 0, 0, 0, 1], 0.6, ['farmers', 0.35], ['IA', 'NE', 'KS', 'FL'], -2,
  'Restore broad federal protection for wetlands and streams',
  'Many marshes and seasonal streams regain Clean Water Act protection. Filling them in would need a federal permit again.',
  'Iowa-ay farmers learn the puddle behind the barn may be a federally protected wetland.',
  ['Wetlands Bill Protects Drinking Water and Flood Defenses', 'Wetland Rule Treats Farm Ditches Like Federal Rivers'],
  'In Sackett v. EPA (2023) the Supreme Court narrowed the Clean Water Act to wetlands with a continuous surface connection to larger waters; Congress can widen that by changing the law.',
  'Wetlands filter water and soak up floods; this keeps them from being paved.', 'More permits, delays and costs for farmers, builders and landowners.',
  'Wetlands are marshes and swamps that clean water and absorb floodwater. A 2023 Supreme Court ruling narrowed which ones the federal Clean Water Act protects. This bill would widen protection again, so filling in many wetlands would need a permit. Supporters say that guards water and prevents floods; farmers and builders say it means more paperwork and delays on their own land.',
  { slot: ['wotus'] }),
P('wildfire', 'Environment', -1, [0.1, 0, 0, 0.3, 2, -1], 0.6, null, ['CA', 'OR', 'CO', 'MT', 'ID'], 3,
  'Fund forest thinning and prescribed burns to curb wildfires',
  'A century of putting out every fire left forests packed with fuel. Crews will clear brush and set small, planned burns.',
  'Californication schedules a fire on purpose. Smokey Bear asks for clarification.',
  ['Wildfire Bill Finally Funds Prevention, Not Just Firefighting', 'Wildfire Plan Is Welcome but Still Tangled in Federal Red Tape'],
  'Researchers widely agree that decades of fire suppression, plus hotter and drier weather, have made many Western forests prone to severe fires; prescribed burns reduce fuel but are limited by smoke rules, staffing and the risk of escapes.',
  'Prevention can cost far less than fighting megafires and rebuilding towns.', 'Costly, slow to show results, and planned burns occasionally escape.',
  'Many Western forests are overgrown because fires were put out for about a century. That extra fuel makes today’s fires bigger and deadlier. This bill pays crews to thin trees and set small, planned fires in safe weather. It costs money now to prevent disasters later, and planned burns cause smoke and sometimes get out of control.'),
// ------------------------------------------------------------------ TRANSPORT
P('cafe', 'Transport', -1, [-0.1, 0, 0.1, 0, 0, 1], 0.6, ['energy', 0.3], ['MI', 'OH', 'TX', 'WY'], -2,
  'Tighten fuel economy standards for new cars and trucks',
  'Car makers must raise the average miles per gallon of what they sell. The pickup truck will be asked to go on a diet.',
  'Michi-gone engineers squeeze two more miles per gallon out of a truck the size of a garage.',
  ['Tougher Mileage Rules Save Drivers Money at the Pump', 'Mileage Mandate Raises Car Prices and Limits Choices'],
  'Fuel economy standards began after the 1970s oil shocks. Economists find they cut fuel use but cost more per gallon saved than a fuel tax, partly because they do not change how much people drive.',
  'Cuts fuel bills, oil imports and pollution over the life of each car.', 'Raises new-car prices and costs more per gallon saved than a fuel tax.',
  'Fuel economy standards set the average miles per gallon a car company’s new vehicles must reach. Stricter standards mean cars that burn less gas, saving drivers money and cutting pollution. But the extra technology raises the price of new cars, and economists say a tax on fuel would get the same savings more cheaply.',
  { slot: ['fuelecon'] }),
P('evcharge', 'Transport', -1, [0.1, 0, 0, 0.3, 1, 0], 0.5, null, ['CA', 'MI', 'GA', 'CO'], 1,
  'Build a national network of fast EV chargers along highways',
  'Cars are getting cleaner and more electric. Now there will be somewhere to plug them in between here and Grandma’s house.',
  'Michi-gone drivers can now charge on the interstate. The vending machine is still out of chips.',
  ['Charger Network Ends Range Anxiety on Road Trips', 'Taxpayer Chargers Built for Cars Many Drivers Do Not Want'],
  'The 2021 infrastructure law set aside $7.5 billion for EV charging, but the rollout was slow; surveys of would-be buyers regularly name too few chargers as a top worry.',
  'Makes electric cars practical everywhere, not just in cities.', 'Government picks a technology, and past charger money was slow to build anything.',
  'With rules pushing car makers toward cleaner and more electric cars, drivers worry about running out of charge on long trips. This bill pays to build fast chargers at regular intervals along major highways. It makes electric cars easier to own, but it costs money, and critics argue private companies would build chargers anyway where people need them.',
  { req: [['gasban', 'cafe']] }),
P('evtax', 'Transport', 1, [0, 0, 0, -0.1, -1, 0], 0.5, null, ['CA', 'WA', 'OR'], -1,
  'Charge electric cars a yearly road fee to replace lost gas tax',
  'Electric cars wear out roads too, but they skip the pump and the gas tax. A yearly fee closes the gap.',
  'Californication EV owners learn the road was never free. It was always paid for at the pump.',
  ['New EV Fee Punishes Drivers for Going Green', 'Electric Cars Finally Pay Their Share for the Roads'],
  'The federal gas tax, 18.4 cents a gallon, has not risen since 1993 and no longer covers highway spending; most states now charge electric cars an extra annual registration fee.',
  'Everyone who uses the roads helps pay for them.', 'Slows the switch to clean cars and adds a cost for early buyers.',
  'Roads are mostly paid for by a tax on each gallon of gas. Electric cars do not buy gas, so their drivers pay little toward roads even though they use them. After you built the charger network, this bill adds a yearly federal fee for electric cars. It is fairer to gas drivers, but it makes electric cars a little less attractive.',
  { req: ['evcharge'], dl: 2 }),
P('hsr', 'Transport', -2, [0.2, -0.1, 0, 0.8, 1, 0], 0.7, null, ['CA', 'TX', 'IL', 'NY'], 1,
  'Build a national high-speed rail network',
  'Trains that go 200 miles an hour between big cities. The first segment opens shortly after the ribbon-cutting committee does.',
  'Californication’s bullet train leaves the station. Its arrival date has been rescheduled.',
  ['High-Speed Rail Brings America Into the Age of Fast Trains', 'Bullet Train Plan Repeats California’s Costly Delays Nationwide'],
  'High-speed lines in Japan and France carry huge numbers of riders between big cities, but California’s project has faced large cost increases and long delays; researchers find US rail and transit construction costs per mile are among the highest in the world.',
  'Fast, clean travel between cities and less crowding on roads and in airports.', 'Enormous cost, long delays, and ridership may fall short of forecasts.',
  'High-speed trains travel up to about 200 miles per hour between big cities. Countries like Japan and France use them heavily. This bill would pay to build a US network. It could cut travel times and pollution, but American rail projects have often gone far over budget and taken many years, and it is uncertain how many people would ride.',
  { slot: ['hsrail'] }),
P('transit', 'Transport', -1, [0, 0, 0, 0.2, 1, 0], 0.5, null, ['NY', 'IL', 'MA', 'PA'], 2,
  'Pay cities to run buses and trains more often',
  'You vetoed the bullet trains. Transit agencies propose the budget option: buses that actually show up every ten minutes.',
  'Illinoise riders wait 8 minutes for a bus instead of 40. One rider sheds a single tear.',
  ['Frequent Buses Help Workers Get to Jobs Without a Car', 'Federal Bus Money Props Up Agencies That Need Reform'],
  'Transit research finds riders care most about how often and how reliably service comes; federal transit money has mostly gone to capital projects such as new lines and vehicles rather than day-to-day service.',
  'A cheap, quick way to make transit useful for millions of riders.', 'Ongoing costs every year, and agencies may come to depend on federal money.',
  'After the expensive high-speed rail plan was vetoed, this bill offers a cheaper way to improve public transportation. It gives cities money to run buses and trains more often, so riders wait less. Federal transit money has mostly gone to building new things rather than running them. It helps riders quickly, but the money must keep flowing every year.',
  { req: ['~hsr'] }),
P('tolls', 'Transport', 1, [0, 0, 0, -0.3, -2, 1], 0.5, ['business', 0.2], ['NJ', 'IL', 'TX', 'PA'], -2,
  'Let states charge tolls on interstates to maintain them',
  'Your infrastructure bill built and fixed roads. Somebody has to pay to keep them fixed, and it may be the person driving on them.',
  'Illinoise drivers meet a new tollbooth. The tollbooth meets a new pothole budget.',
  ['Interstate Tolls Hit Commuters Who Can Least Afford Them', 'Tolls Make Drivers Pay for What They Use Instead of Taxpayers'],
  'Federal law has largely banned tolls on existing interstates since the 1950s, with a few pilot exceptions; economists generally favor road user fees because they link costs to use and can ease congestion.',
  'Drivers who use the roads pay for them, and the new roads get maintained.', 'Hits commuters and truckers, and low-income drivers feel it most.',
  'After the big infrastructure bill, new and repaired roads need upkeep for decades. Federal law mostly forbids tolls on existing interstate highways. This bill lets states charge them. It makes drivers who use the roads pay for them and can cut traffic jams, but it adds a cost for commuters and truckers, which can be passed on in prices.',
  { req: ['infra'] }),
// ------------------------------------------------------------------ TECH
P('aireg', 'Tech', -1, [-0.1, 0, 0, 0, 1, 0], 0.6, ['business', 0.25], ['CA', 'WA', 'NY'], -1,
  'Require safety testing for the most powerful AI systems',
  'Companies training the largest AI models must test them for dangerous abilities and report the results before release.',
  'Californication AI labs are asked to show their homework. The AI offers to write it.',
  ['AI Safety Rules Put Guardrails on a Powerful Technology', 'AI Rules Could Hand the Lead to China, Tech Firms Warn'],
  'The EU passed a broad AI Act in 2024 with extra duties for the most capable models; the US has relied mostly on voluntary commitments and executive orders, and experts disagree on how much risk testing can catch.',
  'Catches serious risks before powerful systems reach millions of users.', 'Compliance costs favor big firms and could slow American innovation.',
  'Artificial intelligence programs are becoming very capable. This bill says companies building the biggest models must test them for dangerous uses, like helping someone make a weapon, and report results to the government before release. Supporters call it common sense for a powerful technology. Critics say the rules may slow innovation and favor big companies that can afford compliance.',
  { slot: ['aireg'] }),
P('privacy', 'Tech', -1, [-0.1, 0, 0, 0, 2, 0], 0.6, ['business', 0.25], ['CA', 'WA', 'VA', 'CO'], 1,
  'Pass a national data privacy law',
  'Apps must ask before selling your data and must let you delete it. Cookie banners remain, sadly, immortal.',
  'Virgin-ia app makers learn the user did not, in fact, agree to share their location with 400 partners.',
  ['Privacy Law Gives Americans Control Over Their Data', 'Privacy Rules Will Bury Small Businesses in Paperwork'],
  'The US has no general federal privacy law, and about 20 states have passed their own. Europe’s GDPR (2018) gave users strong rights; some studies found it also raised compliance costs and reduced the number of apps available.',
  'One clear national rule protects users and ends a patchwork of state laws.', 'Compliance costs hit small firms hardest and may entrench big tech.',
  'Apps and websites collect huge amounts of information about you and often sell it. The US has no single national privacy law, just a patchwork of state rules. This bill would let you see, delete and refuse the sale of your data nationwide. It protects users, but following the rules costs money, which is harder for small companies than for giants.',
  { slot: ['privacy'] }),
P('broadband', 'Tech', -1, [0.1, 0, 0, 0.3, 2, 0], 0.5, null, ['MS', 'WV', 'MT', 'WY'], 3,
  'Subsidize high-speed internet for rural areas',
  'If the nearest fast internet is in the next county, the government helps run cable down your road.',
  'Wyo-Mingle ranch gets broadband. The cows begin livestreaming.',
  ['Rural Broadband Bill Closes the Digital Divide', 'Billions for Rural Internet, With a Track Record of Slow Results'],
  'Millions of rural homes lack fast internet because running lines to scattered houses is costly; past federal programs spent billions, and the large program funded in 2021 took years before construction began.',
  'Lets rural families work, learn and see doctors online.', 'Very costly per home, and past programs moved slowly.',
  'Fast internet is now needed for school, work and even doctor visits. In the countryside, houses are far apart, so companies often decide it does not pay to run cables. This bill uses tax money to cover part of the cost. It helps rural families, but each connection can be expensive, and similar programs have been slow.'),
P('ipo', 'Finance', 2, [0.2, 0, 0, 0, 0, 0], 0.5, null, ['CA', 'NY', 'UT', 'MA'], 1,
  'Ease reporting rules so smaller companies can go public',
  'Young companies could sell stock to the public with lighter paperwork for their first years.',
  'Utah-pia startups ring the opening bell. The bell asks for a shorter filing.',
  ['Wall Street Gets Looser Rules and Investors Get Less Information', 'Easier Path to the Stock Market Lets Ordinary Investors Buy In Early'],
  'The number of US-listed public companies is far below its late-1990s peak. The 2012 JOBS Act eased rules for young firms; studies disagree on how much it increased IPOs, and some raised concerns about investor protection.',
  'Lets ordinary investors share in fast-growing firms early.', 'Less disclosure means more risk of fraud and bad bets for small investors.',
  'Going public means a company sells shares on the stock market, so anyone can own a piece. Public companies must file detailed reports, which is costly for small firms. This bill eases those rules for younger, smaller companies. It could give regular investors more chances to share in growth, but less information means more risk of losses or fraud.'),
P('smallbiz', 'Finance', -1, [0.2, -0.1, 0, 0.2, 2, 0], 0.5, null, ['OH', 'PA', 'GA', 'NC'], 2,
  'Expand federal loan guarantees for small businesses',
  'Banks lend more to new shops and startups when Washington promises to cover much of any loss.',
  'Carolin-ah bakery gets a loan. Its credit history consists of one very good croissant.',
  ['Small Business Loans Help Main Street Compete With Giants', 'Taxpayers Backstop Risky Loans Banks Would Not Make Alone'],
  'The Small Business Administration guarantees part of loans made by private banks; research finds guarantees expand credit, but some loans would have been made anyway and defaults cost taxpayers.',
  'Helps new firms get credit, creating jobs and competition.', 'Taxpayers carry losses, and some loans would have happened anyway.',
  'New businesses often struggle to borrow because banks see them as risky. Under this bill, the government promises to repay a large share of a loan if the business fails, so banks lend more. It helps people start and grow companies, but when loans go bad, taxpayers pay, and some guaranteed loans would have been made without help.'),
P('antitrust', 'Tech', -1, [0, 0, -0.1, 0, 2, 0], 0.6, ['business', 0.3], ['CA', 'WA'], -1,
  'Ban big online platforms from favoring their own products',
  'Instead of breaking up the tech giants, set rules: the store may not bury rivals’ products below its own.',
  'Washingtoon search results now show a competitor first. The competitor faints.',
  ['Fair-Play Rules Give Small Sellers a Real Shot Online', 'New Platform Rules Could Break Features Users Like'],
  'The EU’s Digital Markets Act (2022) bars the largest platforms from favoring their own services; a similar US bill cleared a Senate committee in 2022 but never reached a floor vote. A federal judge ruled in 2024 that Google illegally kept a search monopoly.',
  'Keeps giant platforms from crushing rivals that depend on them.', 'Could break popular features and is hard to enforce fairly.',
  'A few big tech companies run the stores, search engines and app markets that other businesses depend on, and they also sell their own products there. This bill says they cannot rig results to favor themselves. It is an alternative to breaking the companies apart. It helps smaller rivals, but critics worry it could break features people like.',
  { req: ['!techbreak'] }),
// ------------------------------------------------------------------ IMMIGRATION
P('seasonal', 'Immigration', 1, [0.2, -0.1, -0.1, 0, 0, 1], 0.6, ['labor', 0.2], ['CA', 'WA', 'FL', 'GA'], 1,
  'Expand visas for seasonal farm and resort workers',
  'More legal visas for harvest crews, crab pickers and ski-lodge staff. The paperwork shrinks from a novel to a short story.',
  'Washingtoon apple growers get their pickers. The apples are relieved.',
  ['Guest Worker Expansion Risks Lower Wages and Abuse', 'Seasonal Visas Keep Crops From Rotting in the Fields'],
  'H-2A farm visas have no annual cap and have grown sharply since the 2010s, while H-2B non-farm seasonal visas are capped at 66,000 a year; employers call the process slow, and advocates report cases of worker abuse.',
  'Fills jobs few Americans take and keeps food prices down.', 'Workers tied to one employer can be underpaid or mistreated.',
  'Farms, fisheries and resorts need lots of workers for a few months a year. Seasonal work visas let people from other countries come legally for that work and then go home. This bill makes more visas available and speeds approval. It helps businesses and keeps prices down, but critics say it can hold down wages and leave workers open to abuse.'),
P('everify', 'Immigration', -1, [-0.1, 0, 0.1, 0, 1, 1], 0.6, ['farmers', 0.4], ['CA', 'TX', 'FL', 'GA', 'AZ'], -1,
  'Require every employer to check workers’ legal status with E-Verify',
  'After the debate over legal immigration, Congress turns to illegal hiring: every new hire gets checked against federal records.',
  'Flori-duh farms run every new hire through a database. The database is also behind on its paperwork.',
  ['E-Verify Mandate Risks Wrongly Flagging Legal Workers', 'E-Verify Mandate Finally Enforces the Law on Hiring'],
  'E-Verify is a free online system that checks a new hire’s documents against federal records and is already required in some states. Studies of state mandates found less employment of likely unauthorized workers, though some of it shifted to self-employment; errors occasionally flag legal workers.',
  'Enforces immigration law at the workplace, where jobs draw illegal migration.', 'Raises labor costs in farming and building, and errors can block legal workers.',
  'E-Verify is an online system that checks whether a new worker is allowed to work in the US. Right now most employers do not have to use it. This bill requires all of them to. It makes illegal hiring harder, but farms and builders that rely on such workers may face shortages and higher costs, and mistakes can wrongly flag citizens.',
  { req: [['visa', '~visa']] }),
P('dreamers', 'Immigration', 0, [0.1, 0, 0, 0, 1, 1], 0.6, null, ['CA', 'TX', 'IL', 'AZ'], 1,
  'Offer permanent legal status to people brought to the US as children',
  'Young adults who arrived as kids and grew up here could earn green cards by working, studying or serving in the military.',
  'Arid-zona graduates get a path to citizenship. The paperwork has a path of its own.',
  ['Dreamers Finally Get Security in the Only Home They Know', 'Legal Status Plan Rewards Illegal Entry Without Fixing the Border'],
  'DACA, created by executive action in 2012, shields several hundred thousand people brought here as children from deportation but gives no permanent status, and court rulings have left its future uncertain.',
  'Lets young people who grew up here work and contribute fully.', 'Critics say it rewards illegal entry and may encourage more of it.',
  'Some people were brought to the US illegally as young children and grew up here. A program called DACA protects many from deportation, but it can be ended at any time. This bill would let them earn permanent legal status by working, studying or serving in the military. Supporters say it is fair to people who made no choice; opponents fear it rewards illegal immigration.'),
// ------------------------------------------------------------------ GOVERNMENT
P('aidcut', 'Government', 1, [0, 0, 0, -0.1, 1, 0], 0.5, ['farmers', 0.1], ['TX', 'OH', 'KS'], 1,
  'Cut foreign aid spending in half',
  'Foreign aid gets halved. Voters are surprised to learn how small the pile was to begin with.',
  'Ohi-NO voters cheer the foreign aid cut, then learn it will not pay for the bridge.',
  ['Aid Cuts Leave the Hungry Behind and US Influence Weakened', 'Charity Begins at Home as Washington Trims Foreign Handouts'],
  'Foreign aid is about 1 percent of federal spending, while polls repeatedly find Americans guess it is around a quarter of the budget. Supporters say it buys influence and fights disease; critics point to waste and dependence.',
  'Saves money and puts American taxpayers first.', 'Saves little, weakens US influence and harms programs like disease relief.',
  'Foreign aid is money the US spends to help other countries, such as fighting diseases, sending food after disasters and supporting allies. It is only about 1 percent of the federal budget. This bill cuts it in half. It saves a little money, but supporters of aid say it saves lives and buys goodwill that helps American security and trade.',
  { slot: ['foreignaid'] }),
P('stockban', 'Government', 0, [0, 0, 0, 0, 3, 0], 0.5, null, ['OH', 'PA', 'WI'], 2,
  'Ban members of Congress from trading individual stocks',
  'Lawmakers write the rules for companies. Under this bill they may not also bet on those companies’ shares.',
  'Capitol Hill brokerage accounts switch to index funds. The thrill is gone, and so is the suspense.',
  ['Stock Ban Ends Insider Advantage on Capitol Hill', 'Stock Trading Ban Wins Rare Applause From Both Parties'],
  'The 2012 STOCK Act requires lawmakers to report their trades, but late filings have been common. Polls show large majorities in both parties back a ban; studies disagree on whether lawmakers’ trades beat the market.',
  'Removes conflicts of interest and rebuilds trust in Congress.', 'May discourage some people from serving, and better enforcement of reporting may be enough.',
  'Members of Congress write laws that affect companies, and they often learn things before the public does. Today they may buy and sell individual stocks if they report it. This bill would make them use broad funds or blind trusts instead. It reduces conflicts of interest and builds trust, though critics say the reporting rules just need better enforcement.'),
P('publicfin', 'Government', -1, [0, 0, 0, 0.1, 1, 0], 0.5, null, ['NY', 'CT', 'ME'], 1,
  'Match small campaign donations with public funds',
  'Give a candidate $50 and public funds add more on top. Candidates may spend fewer evenings calling big donors.',
  'Maine-ly small donors find their $20 now counts like $120.',
  ['Small-Donor Matching Gives Regular People a Louder Voice', 'Taxpayer Money for Campaigns Funds Politicians Voters Dislike'],
  'New York City has matched small donations for decades, and studies found it widened the range of people who give; critics point to the cost and to matched candidates who were never competitive.',
  'Gives regular donors more weight compared with wealthy givers.', 'Uses tax money for campaigns, including candidates taxpayers oppose.',
  'Running for office costs a lot, so candidates spend much of their time asking wealthy people for money. This bill uses public money to multiply small donations, for example adding several dollars for each dollar from a small donor. It could make ordinary donors matter more, but taxpayers end up funding campaigns, including ones they disagree with.',
  { slot: ['campfin'] }),
P('electaudit', 'Government', 0, [0, 0, 0, 0.1, 1, -1], 0.5, null, ['GA', 'AZ', 'PA', 'WI'], 1,
  'Fund paper ballot backups and post-election audits in every state',
  'Every vote gets a paper record, and states hand-check a random sample to confirm the machines counted right.',
  'Georgia-ish auditors hand-count a sample. The math checks out and everyone goes home for dinner.',
  ['Paper Trails and Audits Build Confidence in Every Vote', 'Audit Funding Is a Sensible Step Toward Trusted Elections'],
  'Most US voters already use paper ballots, and a growing number of states run risk-limiting audits, which hand-check a random sample of ballots; election officials from both parties have backed audits as a way to confirm results.',
  'Lets officials confirm results and builds trust across parties.', 'Costs money and staff time, and states object to federal strings.',
  'Elections in the US are run by states and counties. This bill pays for every voting machine to produce a paper record and for states to hand-check a random sample of ballots after each election, a process called an audit. It helps catch errors and builds trust in results, but it costs money and some states dislike federal rules on how they run elections.'),
P('civilserv', 'Government', 1, [0.1, 0, 0, -0.1, 0, 1], 0.5, ['labor', 0.3], ['VA', 'MD'], -2,
  'Make it easier to fire poorly performing federal employees',
  'Removing a federal worker can take many months. This shortens appeals for performance problems while keeping the ban on political firings.',
  'Virgin-ia commuters debate whether this is reform or a really long pink slip.',
  ['Firing Rules Rewrite Risks a Return to Political Spoils', 'Accountability Finally Comes to the Federal Workforce'],
  'Surveys of federal employees have found many think their agencies fail to deal with poor performers; the 1883 Pendleton Act created civil-service protections to stop jobs being handed out as political rewards.',
  'Lets managers reward good work and remove poor performers faster.', 'Weaker protections could let future leaders fire workers for political reasons.',
  'Most federal workers are protected by civil-service rules, created to stop politicians from handing out government jobs to supporters. Those rules also make firing someone for bad work slow. This bill speeds up that process while still banning political firings. Supporters say it improves government; critics fear weaker protections could be abused.',
  { slot: ['civilserv'] }),
// ------------------------------------------------------------------ SAFETY
P('police', 'Safety', -1, [0, 0, 0, 0.1, 2, -1], 0.5, null, ['IL', 'MO', 'LA', 'TN'], 2,
  'Fund grants to hire 100,000 more local police officers',
  'Washington helps cities hire more officers, the way it did in the 1990s.',
  'Missouri-ous police chiefs post "Now Hiring" signs. The applicants arrive slowly but in uniform.',
  ['More Police Without Reform Repeats the Mistakes of the 1990s', 'Police Funding Bill Puts More Officers on Dangerous Streets'],
  'The 1994 crime law’s COPS program helped fund roughly 100,000 officers; several studies find more police reduce violent crime, while also increasing arrests for minor offenses.',
  'More officers on patrol lower violent crime, studies suggest.', 'Costly, and more minor arrests can strain trust in some neighborhoods.',
  'Local police departments are mostly paid for by cities and states. This bill sends federal money to help them hire more officers. Research suggests more police tend to lower serious crimes like murders and robberies. It costs money, though, and more officers can also mean more arrests for small offenses, which can hurt trust in some communities.'),
P('bodycam', 'Safety', -1, [0, 0, 0, 0.1, 1, -1], 0.5, null, ['MN', 'MO', 'MD'], 1,
  'Require departments that take the new police grants to use body cameras',
  'You funded more officers. This attaches a condition: departments taking the money must use body cameras and keep the video.',
  'Minnesnowta officers clip on cameras. The footage is mostly paperwork and coffee.',
  ['Body Cameras Bring Accountability to Federally Funded Police', 'Camera Mandate Adds Costs, but Many Officers Welcome the Footage'],
  'Body camera studies have mixed results: some found fewer complaints and uses of force, while a large trial in Washington, DC found little effect. Storing and reviewing video is a major ongoing cost.',
  'Creates a record that protects both the public and honest officers.', 'Video storage is costly, and research shows mixed effects on behavior.',
  'After you funded more police officers, this bill says departments taking that money must give officers body cameras. The cameras record what happens during stops and arrests. Video can settle disputes and protect both residents and officers, but studies disagree on how much it changes behavior, and storing years of video is expensive.',
  { req: ['police'] }),
P('footage', 'Safety', -1, [0, 0, 0, 0, 1, -1], 0.5, null, ['MN', 'IL'], 1,
  'Require release of body camera video of serious incidents within 45 days',
  'The cameras are rolling. This sets rules on when the public gets to see the footage, with privacy protections for victims and bystanders.',
  'Illinoise residents get to see the video. The lawyers get to see it first.',
  ['Timely Video Release Lets the Public See What Happened', 'Rushing Video Out Could Harm Investigations, Prosecutors Warn'],
  'Rules on releasing police video vary widely by state and city; some set fixed deadlines after shootings, while others let agencies withhold footage during investigations or block release entirely.',
  'Openness builds trust and stops rumors from filling the silence.', 'Early release can hurt investigations and the privacy of people on video.',
  'Now that officers wear body cameras, the question is who gets to see the video. This bill says footage of serious incidents, like police shootings, must be released within 45 days, with the faces of bystanders and victims blurred. It helps the public know what happened, but prosecutors worry it could affect investigations and trials.',
  { req: ['bodycam'], dl: 2 }),
P('cvi', 'Safety', -1, [0, 0, 0, 0.1, 1, -1], 0.5, null, ['IL', 'MD', 'PA', 'LA'], 1,
  'Fund community programs that work to stop shootings before they happen',
  'After the police-hiring debate, a different tool: trained outreach workers who step in to calm disputes before they turn violent.',
  'Pennsyl-vanity outreach workers talk down a long feud. The feud was about a parking spot.',
  ['Violence Interrupters Save Lives Where Arrests Alone Fail', 'Violence Programs Get Money Despite Mixed Evidence'],
  'Community violence intervention programs, such as Cure Violence and focused deterrence, have been linked to fewer shootings in some cities but not in others; results depend heavily on how well they are run.',
  'Stops shootings early using trusted local messengers.', 'Evidence is mixed, and quality varies a lot between programs.',
  'Much gun violence involves a small number of people caught in ongoing disputes. These programs hire trusted local people, sometimes former gang members, to step in, calm conflicts and connect people to jobs or counseling. They can work alongside policing. Some cities saw fewer shootings, but others did not, so results depend on how well a program is run.',
  { req: [['police', '~police']] }),
P('sentreform', 'Safety', 0, [0, 0, 0, -0.1, 1, 0], 0.5, null, ['TX', 'GA', 'KY'], 0,
  'Cut mandatory minimum sentences for nonviolent drug crimes',
  'Judges get more say in sentencing low-level drug offenders, instead of a fixed number of years set by law.',
  'Kentuckyard judges get their discretion back. Some are not sure where they left it.',
  ['Sentencing Reform Eases Decades of Overcrowded Prisons', 'Shorter Sentences Must Not Mean Weaker Public Safety, Prosecutors Say'],
  'Federal mandatory minimums expanded in the 1980s; the bipartisan First Step Act (2018) eased some of them. Research finds a higher chance of being caught deters crime more than longer sentences do.',
  'Saves prison costs and lets judges fit the sentence to the person.', 'Fixed sentences keep punishments consistent and help prosecutors pursue bigger dealers.',
  'A mandatory minimum is a sentence set by law that a judge cannot go below. Many apply to drug crimes. This bill lowers them for nonviolent drug offenses so judges can decide. It saves prison costs and avoids very long sentences for minor roles, but critics say fixed sentences keep punishments consistent and help prosecutors pursue bigger dealers.',
  { slot: ['sentencing'] }),
P('reentry', 'Safety', -1, [0, 0, 0, 0.1, 1, 0], 0.5, null, ['TX', 'OH', 'GA'], 1,
  'Fund job training and housing help for people leaving prison',
  'With shorter sentences, more people are coming home sooner. This helps them find work and a place to live so fewer go back.',
  'Ohi-NO welding classes fill with former inmates. The instructor says they always show up on time.',
  ['Reentry Help Gives People a Real Second Chance', 'Reentry Funding Is Cheaper Than Paying for Repeat Offenders'],
  'Federal data show a large share of people released from state prisons are rearrested within a few years; the 2008 Second Chance Act funds reentry programs, whose results range from strong to none depending on design.',
  'Helps people stay out of prison, which saves money and prevents crime.', 'Costs money, and many programs show little effect in careful studies.',
  'After you cut some mandatory sentences, more people leave prison sooner. Many struggle to find jobs or housing, and a large share end up back behind bars. This bill pays for training, job placement and temporary housing. If it works, there is less crime and lower prison costs, but studies of such programs have mixed results.',
  { req: ['sentreform'] }),
P('expunge', 'Safety', 0, [0.1, -0.1, 0, 0, 0, 0], 0.5, null, ['PA', 'MI', 'UT'], 1,
  'Automatically seal old records for minor offenses after years without a new crime',
  'People who stayed out of trouble for years get their minor records sealed, so a decade-old mistake stops blocking job offers.',
  'Utah-pia job applicants find their old records sealed. Background-check firms find their margins sealed too.',
  ['Clean Slate Law Removes a Lifelong Barrier to Work', 'Sealed Records Leave Employers and Landlords in the Dark'],
  'Pennsylvania passed the first automatic clean slate law in 2018, followed by Utah, Michigan and other states. A study of Michigan’s record-clearing found people saw higher wages afterward and rarely reoffended.',
  'Helps people work and support families, lowering the risk of new crime.', 'Employers and landlords lose information they say they need.',
  'A criminal record can block someone from jobs and apartments long after they served their sentence. Now that reentry programs help people coming home, this bill goes further: records for minor offenses are sealed automatically after years with no new crime. It helps people work, but employers and landlords lose information they say helps them decide.',
  { req: ['reentry'], dl: 2 })
];
