import { P } from './p.js';
export const HEALTH_EDU = [
// ------------------------------------------------------------------ HEALTH
P('medneg', 'Health', -1, [-0.1, 0, 0, -0.4, 3, 0], 0.5, ['business', 0.25], ['FL', 'AZ', 'ME'], 2,
  'Let Medicare negotiate prices on many more drugs',
  'Medicare already haggles over a handful of drugs. This bill hands it a much longer shopping list.',
  'Pill prices sink; drug-company stock prices have a slightly worse day.',
  ['Seniors Save at the Pharmacy as Drug Makers Lose a Haggling Match', 'Price Controls on Medicine? Drug Makers Warn of Fewer Future Cures'],
  'A 2022 law let Medicare negotiate prices for a short list of high-cost drugs, phased in from 2026; CBO estimated those talks would save roughly $100 billion over a decade.',
  'Lowers what Medicare and seniors pay for drugs.', 'Lower profits may mean fewer new drugs in the long run.',
  'Medicare is the government health plan for people 65 and older. Since 2022 it may bargain over the prices of a small number of drugs; this bill lets it bargain over many more, like one huge shopper asking for a bulk discount. Patients and taxpayers save money, but drug companies earn less and might develop fewer new medicines.',
  { slot: ['drugprice'] }),
P('drugimport', 'Health', 1, [-0.05, 0, -0.1, -0.1, 1, 0], 0.7, null, ['FL', 'VT', 'NH'], 1,
  'Allow imports of cheaper prescription drugs from abroad',
  'If it is made in a licensed plant overseas and costs half as much, you may buy it.',
  'Pharmacists check the Canadian label and the American price tag.',
  ['Cross-Border Pill Shopping Becomes Legal and Slightly Less Awkward', 'Imported Medicine Plan Raises Safety Questions at the Border'],
  'Brand-name drugs cost far more in the US than in peer countries, but limited foreign supply and safety checks cap how much importing can save.',
  'More competition pushes prices down.', 'Hard to guarantee safety, and foreign supply is limited.',
  'Many medicines cost much less in Canada and Europe than in the US. This policy lets pharmacies and patients buy approved drugs from other countries. It adds competition and can lower prices, but regulators must make sure imported medicine is safe, and other countries may not have enough to sell.'),
P('pricetrans', 'Health', 1, [-0.05, 0, -0.1, 0, 1, 0], 0.5, null, ['UT', 'CO', 'TX'], 1,
  'Fine hospitals that hide their prices',
  'The new health accounts only work if patients can see prices. Hospitals that keep them secret would pay real fines.',
  'Hospitals publish prices. Patients discover the prices were not the same.',
  ['Hospitals Must Post Prices, but Patients in an Ambulance Still Cannot Shop', 'Price Shopping Gets Real as Hospitals Post Prices or Pay Up'],
  'A federal rule has required hospitals to post prices since 2021; early compliance was patchy, regulators later raised the penalties, and posted prices for one procedure can differ several-fold within a city.',
  'Gives patients and employers the prices they need to compare.', 'Adds compliance costs, and patients cannot shop in an emergency.',
  'Health savings accounts are meant to let patients shop for care, but shopping is hard when prices are secret. A federal rule already says hospitals must post prices, yet many were slow to obey. This bill adds large fines for hiding them. Prices may fall as hospitals compete, but posted lists can be confusing and nobody shops in an emergency.',
  { req: ['hsa'] }),
P('medadv', 'Health', -1, [0, 0, 0, -0.6, -1, 0], 0.5, ['business', 0.3], ['FL', 'AZ', 'TX'], -2,
  'Cut overpayments to private Medicare Advantage plans',
  'Private plans that cost Medicare more per person than regular Medicare get a pay cut.',
  'Insurers warn of changes to benefits. Auditors say "finally."',
  ['Government Trims Overpayments to Insurers, Saves Billions', 'Seniors Warned Their Extra Benefits May Disappear'],
  'MedPAC, which advises Congress, estimates Medicare pays Medicare Advantage plans roughly 20 percent more per person than the same people would cost in traditional Medicare.',
  'Saves money and ends payments above actual costs.', 'Plans may cut the extras that many seniors like.',
  'Medicare Advantage lets seniors pick a private insurance company to run their Medicare benefits. Studies find the government pays these companies more per person than regular Medicare costs. Cutting the payments saves taxpayer money, but the plans may drop extra benefits like gym memberships or dental coverage.',
  { sys: ['privins'] }),
P('pubop', 'Health', -2, [-0.2, 0.1, 0, 0.5, 3, 1], 0.8, ['business', 0.35], ['MN', 'CO', 'NY'], 2,
  'Create a public health insurance option',
  'A government plan competes with private insurers on the health exchanges.',
  'The government opens an insurance company. The other insurance companies open a lobbying office.',
  ['Public Option Passes: Choice, Competition, and a Nicer Waiting Room Poster', 'Government Insurance Plan Launches; Private Insurers Call It "Unfair Competition"'],
  'Cost and savings estimates swing widely with the payment rates chosen; Washington and Colorado have launched state versions, with mixed early results on premiums and enrollment.',
  'Adds a lower-cost choice and competition for insurers.', 'Could underpay doctors and crowd out private plans over time.',
  'A public option is a health insurance plan run by the government that people could choose instead of a private plan. It adds competition and could lower premiums. Supporters see a step toward universal coverage; critics worry it would pay doctors too little and slowly push private insurers out.',
  { slot: ['healthsys'], sys: ['privins'] }),
P('medicare60', 'Health', -2, [-0.1, 0, 0, 0.5, 3, 0], 0.6, ['business', 0.2], ['FL', 'OH', 'PA'], 3,
  'Let people 60 and older buy into Medicare',
  'A compromise after the public-option fight: near-retirees may join Medicare early.',
  'Sixty is the new sixty-five, at least for insurance purposes.',
  ['Early Medicare Buy-In Brings Relief to Early Retirees', 'Medicare Expansion Raises Questions About an Already Strained Fund'],
  'People aged 60 to 64 are too young for Medicare and face high premiums in the individual market, because insurers may charge older adults up to three times what they charge young adults; a buy-in would let them pay into Medicare instead.',
  'Gives older people who are not yet eligible affordable coverage.', 'Those who join may be sicker than average, and hospitals would get Medicare’s lower rates.',
  'Medicare normally starts at 65. This bill would let people 60 to 64 pay to join early. Private insurance is costly at those ages because health problems grow with age. It helps early retirees, but the people who sign up may be sicker than average, and hospitals worry about being paid Medicare’s lower rates.',
  { req: ['~pubop'], slot: ['healthsys'] }),
P('formulary', 'Health', -2, [-0.2, 0.1, -0.1, -0.8, 0, 1], 0.6, ['business', 0.4], ['NJ', 'MA', 'PA'], -1,
  'Create one national list of covered drugs',
  'Now that one plan covers everyone, it must decide which drugs to cover. Everyone will have opinions.',
  'A single list of covered drugs. A very long argument about the list.',
  ['National Drug List Cuts Costs and Confusion', 'Government Committee Decides Which Medicines Count'],
  'Countries with one national payer typically use a formulary and a review board to decide what the public plan will cover.',
  'Buys drugs in bulk, saves money, and ends insurer-by-insurer paperwork.', 'A committee decides what is covered; patients may wait for newer drugs.',
  'A formulary is the official list of medicines a health plan will pay for. With one national plan, there is one list for the whole country. It can save money and simplify things, but patients might not get a newer or pricier medicine until the government approves it.',
  { req: ['sp'], dl: 2 }),
P('hsaexp', 'Health', 1, [0.1, 0, 0, 0.3, 1, 0], 0.5, null, ['UT', 'TX', 'AZ'], 1,
  'Let health savings accounts pay premiums and hold more money',
  'The new accounts could pay monthly insurance premiums and take bigger yearly deposits.',
  'Health savings accounts get roomier. Tax preparers get busier.',
  ['Savings Accounts Expand; Families With Low Incomes Ask What They Are Saving', 'Bigger Health Savings Accounts Put Patients in Charge of Their Own Dollars'],
  'Health savings accounts are used mostly by higher earners, in part because the tax break is worth more at higher tax rates.',
  'Gives people more control and a reason to shop carefully.', 'Mostly helps people who have extra money to save.',
  'A health savings account is a special savings account for medical costs: money you put in is not taxed. Today it mostly cannot pay insurance premiums, and deposits are capped each year. This bill lets it pay premiums and raises the cap. It gives families more control, but people with low incomes often cannot afford to set money aside.',
  { req: ['hsa'], sys: ['privins', 'deduct'] }),
P('scopeprac', 'Health', 1, [0.2, -0.1, -0.1, -0.1, -1, 0], 0.5, null, ['GA', 'AL', 'MS'], 1,
  'Let nurse practitioners treat patients without a doctor’s sign-off',
  'In many places a nurse can diagnose you but needs a doctor’s signature to do it.',
  'More clinics open in small towns. Doctors form a committee.',
  ['Nurse Practitioners Get Green Light; Rural Clinics Reopen', 'Medical Groups Warn Against Letting Non-Doctors Work Alone'],
  'Many states already let nurse practitioners practice independently; studies generally find similar quality for routine care and better access in rural areas.',
  'More access to care, especially in rural areas, at lower cost.', 'Doctors argue complex cases need physician oversight.',
  'Nurse practitioners are nurses with advanced training who can diagnose and treat many problems. In many states they must have a doctor sign off on their work. This bill sets a national rule removing that requirement. It can open more clinics in small towns, though doctors warn that harder cases need a physician involved.',
  { slot: ['scope'] }),
P('certneed', 'Health', 2, [0.2, -0.1, -0.1, 0.1, 0, 0], 0.6, null, ['NC', 'TN', 'GA'], 0,
  'Repeal certificate-of-need laws for new hospitals',
  'You would no longer need the government to agree your town "needs" a new clinic before you build one.',
  'A new clinic opens across the street from the old hospital. The old hospital notices.',
  ['Safety Net Hospitals Warn About Cherry-Picking', 'Hospital Boom: New Clinics No Longer Need a Rival’s Blessing'],
  'About 35 states require a government certificate of need before building some health facilities; research on whether repeal lowers costs is mixed.',
  'More competition and more places to get care.', 'New facilities may take the profitable patients and leave safety-net hospitals strapped.',
  'In many states a hospital must prove to the government that the community "needs" a new facility before it can be built. Critics say this protects existing hospitals from competition. This bill would override those state rules. It could mean more clinics and lower prices, though older hospitals could struggle.'),
P('medmal', 'Health', 2, [0.1, 0, 0, -0.1, -2, 1], 0.6, null, ['NY', 'PA', 'IL'], -1,
  'Cap pain-and-suffering damages in malpractice lawsuits',
  'Patients who win a lawsuit would receive a limited amount for pain and suffering.',
  'Insurance premiums for doctors fall. So do some jury awards.',
  ['Injured Patients Say the Cap Shrinks Justice', 'Doctors Cheer Cap on Lawsuit Payouts'],
  'Studies find caps reduce malpractice insurance costs, but savings from less "defensive medicine" are smaller than often claimed.',
  'Lowers doctors’ insurance costs and may limit unneeded tests.', 'Limits what injured patients can recover.',
  'Malpractice means a medical mistake that hurts a patient. Patients can sue for money. This bill puts a limit on the amount a jury can award for pain and suffering. Doctors pay less for insurance, but patients with the most serious injuries may get less than they lost.'),
P('telehealth', 'Health', 0, [0.1, 0, 0, 0.2, 2, 0], 0.4, null, ['MT', 'WV', 'KS'], 2,
  'Make Medicare telehealth coverage permanent',
  'A video appointment with a doctor, from the couch, would stay covered instead of depending on short extensions.',
  'Doctors see patients through screens. The screens are very proud.',
  ['Telehealth Stays; Rural Patients Save Hours on the Road', 'Telehealth Costs Climb as Visits Multiply'],
  'Telehealth use jumped during the pandemic; evidence is strongest for mental health and follow-up visits, weaker for conditions that need a physical exam.',
  'Saves travel time and widens access in rural areas.', 'Visits can multiply, raising total spending.',
  'Telehealth means seeing a doctor by phone or video instead of in an office. During the pandemic Medicare greatly expanded what it pays for as an emergency measure, and Congress has extended that rule several times. Making it permanent helps people far from clinics, but more visits can raise what the government pays in total.'),
P('nursefund', 'Health', -1, [0.1, -0.1, 0, 0.3, 2, 0], 0.5, null, ['OH', 'NC', 'MI'], 2,
  'Fund nursing schools to fix the nurse shortage',
  'Grants for faculty and clinical seats, so qualified applicants stop being turned away.',
  'Nursing schools expand. Applicants stop getting waitlisted.',
  ['Nursing Schools Grow to Meet Hospital Shortage', 'Nurse Funding Plan Draws Criticism for Slow Payoff'],
  'Nursing schools turn away tens of thousands of qualified applications a year, mostly for lack of faculty and clinical training spots.',
  'Fills a real shortage and creates stable jobs.', 'Takes years to pay off and costs money up front.',
  'Hospitals across the country say they cannot find enough nurses. Many people who want to become nurses are turned away because schools lack teachers and training spots. This bill pays for more of both. It adds jobs and helps hospitals, but the benefits take years to show up.'),
P('sugar', 'Health', -1, [-0.1, 0, 0.1, -0.3, -2, 1], 0.5, ['business', 0.25], ['MS', 'AL', 'GA'], -2,
  'Tax sugary drinks',
  'A penny-per-ounce tax on soda. Fizzy politics ensue.',
  'Soda costs more. Water bottles have a good week.',
  ['Soda Tax Raises Revenue and Public Health Hopes', 'Grocery Bills Rise as Soda Tax Fizzes Into Law'],
  'Cities with soda taxes, such as Philadelphia and Berkeley, saw sales of taxed drinks fall noticeably, though some shoppers bought across the city line instead.',
  'Reduces sugar consumption and raises revenue.', 'Regressive: it hits lower-income households hardest.',
  'A soda tax adds a fee to sugary drinks. The idea is to nudge people toward healthier choices and raise money for health programs. Studies show people buy less soda when it costs more, but the tax takes a bigger share of a poor family’s budget than a rich family’s.'),
P('biotechip', 'Health', 1, [0.1, 0, 0.1, 0.1, 1, 0], 0.5, null, ['MA', 'NC', 'CA'], 1,
  'Lengthen protection from copies for new biologic drugs',
  'Drug makers asked for something in return for the price talks: more time before cheaper copies arrive.',
  'Drug makers get more time to sell their new medicine without copies.',
  ['Protection Extended, Delaying Cheaper Copies of Costly Drugs', 'Longer Protection Rewards the Risky Work of Inventing Cures'],
  'Since 2010, new biologic drugs get 12 years before cheaper copies called biosimilars can be approved; drug makers argue price negotiation shrinks their window to earn back research costs.',
  'Keeps the reward for developing new medicines.', 'Delays cheaper copies and keeps prices high longer.',
  'Biologics are complex medicines made from living cells. A new one gets years of protection before other companies may sell cheaper copies. This bill makes that protection longer. It rewards the companies that spend a lot to invent new drugs, but it also keeps prices high for longer, including for Medicare.',
  { req: ['medneg'] }),
P('insulincap', 'Health', -1, [0, 0, 0, 0.1, 3, 0], 0.3, null, ['MS', 'WV', 'AL'], 2,
  'Cap insulin copays at $35 a month in private insurance plans',
  'People with diabetes on private plans would pay no more than $35 for a month of insulin.',
  'Insulin copays shrink. Pharmacists notice the line is shorter.',
  ['Insulin Cap Brings Relief to Millions With Diabetes', 'Insulin Cap Shifts Costs to Everyone Else’s Premiums'],
  'Medicare has capped insulin at $35 a month since 2023; many states cap private plan copays, and surveys found some patients had been rationing doses.',
  'Protects patients from rationing a lifesaving drug.', 'Costs shift to insurers and may raise premiums slightly.',
  'Insulin is a medicine many people with diabetes must take every day to stay alive. Its price rose sharply for years. A copay cap means a patient pays at most $35 a month; the insurance company covers the rest. It helps patients, but the cost can raise insurance premiums a little for everyone.',
  { sys: ['privins'] }),
P('aca', 'Health', -1, [0.1, -0.1, 0, 0.5, 3, 0], 0.5, null, ['FL', 'TX', 'GA'], 3,
  'Make the larger health-insurance marketplace subsidies permanent',
  'Help paying for marketplace plans would be locked in at the higher level instead of expiring or being renegotiated.',
  'Premiums stay lower for millions. The Treasury stays a little lower too.',
  ['Premium Help Made Permanent, Coverage Stays at Record Levels', 'Permanent Subsidies Add Billions to a Growing Deficit'],
  'Larger subsidies first passed in 2021 helped push marketplace enrollment to records above 20 million; CBO estimated a permanent extension would cost on the order of $350 billion over ten years.',
  'Keeps coverage affordable for millions.', 'Adds hundreds of billions in federal spending.',
  'The Affordable Care Act (ACA) set up online marketplaces where people can buy health insurance and get tax credits to help pay for it. In 2021 Congress made the help bigger, but only for a limited time, and it has been fought over since. Making it permanent keeps premiums lower for millions, but it costs the government a lot every year.',
  { sys: ['privins', 'deduct'] }),
// ------------------------------------------------------------------ EDUCATION
P('charter', 'Education', 1, [0.1, 0, 0, 0.1, 0, 1], 0.6, ['labor', 0.2], ['AZ', 'NY', 'LA'], 0,
  'Expand public charter schools',
  'A middle path after the voucher veto: more school choice, but inside the public system.',
  'More charter schools open. More district meetings about charter schools.',
  ['Charter Expansion Pulls Money From District Schools', 'Charter School Waiting Lists Shrink as New Campuses Open'],
  'Studies find large gains in some urban charter networks and flat or negative results in others; results depend heavily on the school and on local rules.',
  'Gives families more choices without leaving public funding.', 'Results vary and districts lose funds for each student who leaves.',
  'A charter school is a public school run by an independent group instead of the local school district. It gets public money but has more freedom to try new methods. Some charter networks do well and some do not. Districts argue the money leaves with the students and their regular schools lose out.',
  { req: ['~vouch'] }),
P('voucheval', 'Education', -1, [0.1, 0, 0, 0.1, 1, 0], 0.4, null, ['WI', 'LA', 'OH'], 0,
  'Require testing and public reports from voucher schools',
  'If public money follows the child, so should a report card.',
  'Voucher schools must publish test scores. Parents read them, finally.',
  ['Voucher Schools Must Publish Results; Parents Get a Look Inside', 'New Testing Rules Burden Small Private Schools'],
  'Evidence on vouchers is mixed, and accountability rules differ widely: some programs require schools to give state tests and report results, while others do not.',
  'Lets families see whether a school delivers.', 'Adds paperwork that small private schools may not want.',
  'When the government pays for a child to attend a private school with a voucher, people want to know whether the school is doing a good job. This bill requires voucher schools to give the same tests as public schools and publish the results. Supporters call it fair; some private schools say it adds red tape.',
  { req: ['vouch'] }),
P('collegecap', 'Education', -1, [0.1, 0, 0, 0.4, 1, 0], 0.5, null, ['WI', 'MN', 'MA'], 1,
  'Fund extra seats and teachers at public colleges',
  'Free tuition is nice, but a seat in the classroom would also help.',
  'Colleges hire instructors. Students can finally enroll in the class they needed.',
  ['Extra Funding Opens Seats as Free College Draws Crowds', 'Free College Plan Gets a Second, Bigger Bill'],
  'Studies link added spending per student at public colleges to higher completion rates, and tuition-free programs can strain capacity if funding does not grow with enrollment.',
  'Makes sure free tuition means a class you can actually take.', 'Adds another large cost to an already expensive program.',
  'If college becomes free, more students will apply. But colleges need teachers, classrooms and advisors for the extra students. This bill adds money so schools can grow and students do not end up on long waiting lists. It costs more, but it helps free tuition keep its promise.',
  { req: ['college'], dl: 2 }),
P('idr', 'Education', -1, [0.1, 0, 0, 0.3, 2, 0], 0.4, null, ['PA', 'OH', 'MI'], 1,
  'Cap student loan payments at a small share of income',
  'A smaller step than canceling debt: monthly payments follow your paycheck, and what is left is forgiven after 20 years.',
  'Student loan payments finally depend on what you earn.',
  ['Borrowers Get Loan Payments They Can Actually Afford', 'Loan Plan Shifts More Debt Costs to Taxpayers'],
  'Income-driven repayment plans have existed since the 1990s; a 2023 plan that cut payments sharply was blocked in court, and the cost depends heavily on how generous the formula is.',
  'Affordable payments and fewer defaults for low earners.', 'Some borrowers will not repay in full, so taxpayers absorb the remainder.',
  'Student loans are normally repaid on a fixed schedule. Income-driven repayment sets your monthly payment as a small percent of what you earn above a basic living amount, and cancels any debt left after many years. It helps borrowers with low pay, but taxpayers cover the debt that is canceled.',
  { req: ['~debt'] }),
P('kinder', 'Education', -1, [0.1, -0.1, 0, 0.5, 2, 0], 0.5, null, ['MN', 'WA', 'MA'], 1,
  'Extend free preschool to three-year-olds',
  'Parents of younger siblings ask why the free year starts at four. This bill adds one more.',
  'Three-year-olds now have a school. They have opinions about nap time.',
  ['Free Preschool Expands to Three-Year-Olds', 'Preschool Expansion Raises Questions About Program Quality'],
  'High-quality programs for three-year-olds show benefits in some studies, but large-scale programs often struggle to keep quality as they grow.',
  'More families get free child care and early learning.', 'Quality can drop as programs scale up quickly.',
  'Pre-K is school for young children before kindergarten. This bill adds a year, so three-year-olds can attend free. It saves parents the high cost of child care and may help children learn, but when a program grows fast it can be hard to keep every classroom high quality.',
  { req: ['prek'], dl: 2 }),
P('tradeschool', 'Education', 0, [0.2, -0.1, 0, 0.3, 2, -1], 0.4, null, ['OH', 'WI', 'TX'], 2,
  'Fund career-and-technical programs in high schools',
  'Welding, health tech and electrical work, taught in high school, with an industry certificate by graduation.',
  'Shop class returns. Guidance counselors learn a new word: "journeyman."',
  ['Career Programs Give Students Without College Plans a Real Path', 'Federal Money for Shop Class Arrives With Federal Paperwork'],
  'Studies of career-focused high schools, including Massachusetts’ regional vocational schools, find higher graduation rates for students who attend; the federal Perkins Act already funds such programs on a modest scale.',
  'Builds skills employers need and keeps more students engaged in school.', 'Only works if the training matches real local jobs.',
  'Career and technical education (CTE) teaches job skills such as welding, auto repair or health technology while students are still in high school. This bill gives schools money for equipment and teachers. It can keep students engaged and help them find good jobs without a four-year degree, if programs match what local employers need.'),
P('teacherpay', 'Education', -1, [0.1, 0, 0, 0.6, 3, 0], 0.5, null, ['AZ', 'OK', 'WV'], 3,
  'Raise teacher pay with federal matching grants',
  'Washington matches state raises, in the hope that a teacher can afford the town where they teach.',
  'Teachers get raises. Class sizes get a little smaller.',
  ['Teacher Raises Ease Shortage in High-Need Schools', 'Teacher Pay Plan Costs Billions Without Fixing Classrooms'],
  'Teacher pay has lagged other college-educated jobs for decades, and shortages are most severe in low-income districts and in subjects like math and special education.',
  'Helps attract and keep good teachers.', 'Pay raises alone do not guarantee better teaching.',
  'Many states pay teachers less than other jobs that need a college degree, and some schools cannot find enough teachers. This bill gives states money if they raise teacher pay. It may help schools keep good teachers, but supporters of other reforms say pay should be tied to results.'),
P('meritpay', 'Education', 1, [0.1, 0, 0, 0.1, -1, 1], 0.6, ['labor', 0.3], ['TX', 'LA', 'FL'], 0,
  'Reward top teachers with merit pay',
  'Federal grants fund bonuses for teachers whose students make the most progress.',
  'Teachers are paid for progress. Every test score is now a high-stakes decision.',
  ['Teachers Say Merit Pay Turns Classrooms Into Test-Prep Factories', 'Merit Pay Rewards Teachers Who Raise Scores'],
  'Research on teacher merit pay is mixed: some studies find modest gains in test scores, others find little effect.',
  'Rewards effective teaching and attracts ambitious teachers.', 'Test scores are an imperfect measure and can encourage teaching to the test.',
  'Merit pay means a teacher can earn more money if students learn more. This bill gives states grants to pay such bonuses. Supporters say it rewards great teachers. Critics say it is hard to measure learning fairly, and that it can push teachers to focus only on what is on the test.'),
P('meals', 'Education', -1, [0.1, 0, 0, 0.4, 3, -1], 0.3, null, ['MS', 'AL', 'NM'], 2,
  'Offer free school meals to every student',
  'Breakfast and lunch for all, so no student gets a lecture about an unpaid balance.',
  'Cafeteria lines get shorter. Lunch debt vanishes.',
  ['Free School Meals End Lunch Line Stigma', 'Universal Meals Cost Billions to Feed Kids Who Could Pay'],
  'Research on universal free meals links them to better attendance and fewer disciplinary problems; the cost is higher than means-tested programs.',
  'Removes stigma and makes sure every child can eat.', 'Spends money on meals for families that could afford to pay.',
  'Many schools give free or cheap meals only to kids from low-income families, which can be embarrassing and requires paperwork. This policy gives meals to every student. It ends stigma and makes sure no child goes hungry, but it also pays for children from wealthier families.'),
P('ccollege', 'Education', -1, [0.2, -0.1, 0, 0.4, 2, -1], 0.4, null, ['MN', 'TN', 'WA'], 2,
  'Make community college free',
  'The first two years of college cost nothing, and nobody has to take on debt for them.',
  'Community colleges fill up. Parking lots do too.',
  ['Free Community College Opens the Door for Thousands', 'Free Tuition Plan Draws Students Who May Not Finish'],
  'Free community college programs such as Tennessee Promise raised enrollment, though completion rates and later earnings have shown smaller improvements.',
  'Opens higher education to people who could not otherwise afford it.', 'Many students do not finish, so some of the money is spent without a degree.',
  'Community college is a two-year college that offers certificates and associate degrees, and a path to a four-year school. This policy makes it free. It helps more people get started, but many students drop out for reasons that tuition alone does not fix.',
  { slot: ['tuition'] }),
P('stem', 'Education', 0, [0.2, -0.1, 0, 0.2, 1, 0], 0.5, null, ['MD', 'VA', 'CO'], 1,
  'Fund STEM scholarships in exchange for public service',
  'Study cybersecurity, engineering or math for free, then work a few years for the government or teach where teachers are scarce.',
  'More engineers graduate without loans. Their first boss is Uncle Sam.',
  ['Scholarships Turn Science Students Into Public Servants', 'Scholarship-for-Service Plan Questioned as Graduates Eye the Exit'],
  'Programs such as CyberCorps, which trains cybersecurity students for government jobs, and NSF’s Noyce scholarships, for STEM majors who then teach in high-need schools, use this model; some participants leave once their commitment ends.',
  'Fills hard-to-staff public jobs and lowers college costs.', 'Participants may leave after the service period ends.',
  'STEM means science, technology, engineering and math. This policy pays college costs for students in those fields if they agree to work for a few years in a government job, such as cybersecurity, or to teach math or science in a school that struggles to hire. It fills important jobs, but some graduates leave once the required time is up.'),
];
