import { P } from './p.js';
export const LHT = [
// ------------------------------------------------------------------ LABOR: minimum wage branch
P('mwindex', 'Labor', -1, [-0.05, 0.05, 0.1, 0, 2, 0], 0.5, null, ['WA', 'OH', 'FL', 'AZ'], 2,
  'Index the new $15 minimum wage to inflation',
  'Now that the floor is $15, it rises with prices every year so Congress never has to vote on it again.',
  'The minimum wage gets an annual raise. Congress gets an annual nap.',
  ['Wage Floor Will Finally Keep Up With Grocery Prices', 'Automatic Wage Hikes Forever, With No Vote Required'],
  'The federal minimum has been $7.25 since 2009, losing value to inflation every year it went unchanged. Many states, including Washington, Ohio and Arizona, now adjust their minimums automatically for inflation.',
  'Stops the wage floor from quietly shrinking and ends decade-long political fights.', 'Locks in raises even in a slump and removes a lever Congress could adjust.',
  'After the minimum wage went to $15, this bill makes it rise automatically each year by the same percentage as prices. That way a $15 paycheck buys the same amount of food and rent in ten years. Workers keep their buying power, but businesses face a raise every year, even in years when sales are bad.',
  { req: ['mw15'], dl: 2 }),
P('smallbizcr', 'Labor', 0, [0.1, -0.1, 0, 0.4, 2, -1], 0.5, null, ['TX', 'GA', 'KY', 'IA'], 2,
  'Give small businesses a tax credit to cushion the $15 minimum wage',
  'Diners and corner stores get a temporary credit for part of their higher payroll, phasing out over five years.',
  'The corner diner gets a tax break. The pie still costs $6.',
  ['Main Street Gets Help Paying Workers a Living Wage', 'Taxpayers Now Subsidize the Wage Mandate They Were Told Was Free'],
  'CBO estimated in 2019 that a $15 federal minimum would raise pay for about 17 million workers but could cost around 1.3 million jobs in its middle estimate, with a wide range; small, low-margin firms feel it most.',
  'Softens the blow for the small employers most likely to cut jobs.', 'Costs taxpayers money and props up firms that cannot afford the wage law.',
  'The $15 minimum wage is hardest on small businesses with thin profits, like diners and family shops. This bill gives them a tax credit, a discount on their taxes, to cover part of the raise for a few years. It could save some jobs, but it costs the government money and means taxpayers help pay a wage that the law requires.',
  { req: ['mw15'], dl: 2, sys: ['inctax', 'deduct'] }),
P('tippedwage', 'Labor', -2, [-0.1, 0.1, 0.1, 0, 1, 0], 0.5, ['business', 0.2], ['NV', 'FL', 'TX', 'GA'], 1,
  'End the $2.13 tipped minimum wage',
  'Servers must get the full $15 before tips, not $2.13 plus whatever the table feels like leaving.',
  'Restaurants reprint menus. A 20% tip is now a mild suggestion.',
  ['Servers Win a Real Paycheck, Not Just a Tip Jar', 'Restaurants Warn of Higher Prices and Fewer Shifts'],
  'The federal tipped minimum has been $2.13 an hour since 1991; employers must top up if tips fall short. Several states, including California and Washington, already require the full minimum before tips.',
  'Steadier pay for servers and less dependence on customer moods.', 'Higher menu prices and fewer server jobs; some servers earn more under tipping.',
  'Under federal law, restaurants can pay servers as little as $2.13 an hour, as long as tips bring them up to the regular minimum. This bill makes restaurants pay the full $15 minimum before tips. Servers get steadier pay, but restaurants may raise prices or hire fewer people, and some servers fear customers will tip less.',
  { req: ['mw15'], dl: 2 }),
P('mwregion', 'Labor', -1, [-0.2, 0.2, 0.2, 0, 3, 0], 0.5, ['business', 0.15], ['CA', 'NY', 'WA', 'MA'], 2,
  'Set a regional minimum wage tied to local living costs',
  'After the $15 veto, a softer version: the floor is higher in expensive cities and lower where rent is cheap.',
  'Manhattan gets $17. Rural Mississippi gets $10. Both get a spreadsheet.',
  ['Wage Floor Finally Matches What Rent Actually Costs', 'Washington Now Sets a Different Wage for Every Zip Code'],
  'BEA’s regional price parities show living costs vary widely, with prices in the costliest states well above those in the cheapest. A single national wage floor bites much harder in low-cost areas than in high-cost ones.',
  'Raises pay where living costs are highest without crushing jobs in cheap regions.', 'Complicated to run and lets low-wage regions stay low-wage.',
  'You vetoed a flat $15 minimum wage. This bill sets a different minimum wage for each region based on how much it costs to live there. Workers in expensive cities get more, while places with cheap rent get a smaller raise so local businesses are not overwhelmed. It is fairer to local costs, but harder to manage and still raises costs for employers.',
  { req: ['~mw15'], dl: 2, slot: ['minwage'] }),
P('eitcmw', 'Labor', 0, [0.2, -0.3, 0.1, 0.8, 3, -1], 0.6, null, ['MS', 'AL', 'KY', 'WV', 'OH'], 3,
  'Pay a federal wage subsidy for low-wage jobs instead of a mandate',
  'Instead of making employers pay more, the government tops up every low-wage paycheck directly.',
  'Your paycheck now has two signatures: your boss and Uncle Sam.',
  ['Uncle Sam Tops Up Paychecks for Low-Wage Workers', 'Big Spending Program Disguised as a Pro-Work Plan'],
  'Economist Edmund Phelps proposed subsidies for low-wage employment in his 1997 book Rewarding Work. Unlike a mandate, a subsidy raises pay without raising employer costs, but it costs the government money, and some of it can leak to employers through lower wages.',
  'Raises take-home pay and encourages hiring rather than discouraging it.', 'Expensive, and employers may pocket part of the subsidy by holding wages down.',
  'Instead of forcing businesses to pay a higher minimum wage, this bill has the government add money to every low-wage paycheck. A worker earning $10 an hour might take home $12. Jobs are not put at risk because employers do not pay more, but taxpayers do, and some companies might keep wages low because they know the government will top them up.',
  { req: [['~mw15', '~mw0']], dl: 2 }),
// ------------------------------------------------------------------ LABOR: unions
P('cardcheck', 'Labor', -2, [-0.1, 0, 0.1, 0, 1, 1], 0.6, ['business', 0.35], ['MI', 'OH', 'PA', 'NV'], 2,
  'Let workers form a union by signing cards (card check)',
  'If most workers sign union cards, the union is recognized, no separate election required.',
  'Union organizers buy pens in bulk. Lawyers buy a second boat.',
  ['Workers Can Finally Unionize Without a Months-Long Fight', 'End of the Secret Ballot Leaves Workers Open to Pressure'],
  'The Employee Free Choice Act of 2009 would have allowed card check and first-contract arbitration but stalled in the Senate. Today about one in ten US workers belongs to a union, down from roughly one in five in 1983.',
  'Cuts delays and employer pressure campaigns before union votes.', 'Workers lose the privacy of a secret ballot and may feel pushed to sign.',
  'Today, workers who want a union usually need a secret-ballot election run by the government, which can take months. Card check lets them form a union once a majority signs cards saying they want one. Unions say this stops bosses from pressuring workers before the vote. Critics say signing a card in front of coworkers is not as private as a secret ballot.',
  { req: [['norw', '~rtw']], dl: 2, slot: ['unionvote'], sys: ['unions'] }),
P('arbitration', 'Labor', -2, [-0.1, 0, 0.1, 0, 1, 0], 0.6, ['business', 0.25], ['MI', 'OH', 'IL'], 2,
  'Send stalled first union contracts to binding arbitration',
  'New unions that cannot reach a first contract within a set number of months get one written by a neutral arbitrator.',
  'Bargaining tables get a referee. The referee brings a stopwatch.',
  ['New Unions Get Their First Contract Instead of Endless Stalling', 'Government Arbitrators Will Now Write Private Company Contracts'],
  'Studies find newly unionized workplaces often take more than a year to reach a first contract, and some never do. Several Canadian provinces use first-contract arbitration to break such deadlocks.',
  'Makes winning a union actually lead to a contract.', 'Lets an outsider set wages and rules that neither side agreed to.',
  'After card check made forming a union easier, many new unions still struggle to agree on a first contract with their employer. This bill says that if talks drag on too long, a neutral expert called an arbitrator decides the terms, and both sides must accept them. It ends stalling, but critics say a stranger should not decide a company’s pay rules.',
  { req: ['cardcheck'], dl: 2, sys: ['unions'] }),
P('secretballot', 'Labor', 1, [0, 0, 0, 0, 0, 1], 0.5, ['labor', 0.3], ['SC', 'TX', 'UT', 'TN'], 1,
  'Require secret-ballot elections for every union vote',
  'No union may be recognized by signed cards or a handshake. Every vote goes in a private booth.',
  'Union drives now come with a curtain and a little "I voted" sticker.',
  ['Union-Busting Bill Adds Hurdles for Workers Who Want to Organize', 'Workers Guaranteed a Private Vote on Joining a Union'],
  'Most union elections are already run by secret ballot through the National Labor Relations Board, but employers can voluntarily recognize unions by card count. Unions argue that long campaigns give employers time to hold mandatory anti-union meetings.',
  'Protects workers from pressure by either the union or the boss.', 'Adds delay and gives employers more time to fight organizing drives.',
  'Workers decide whether to form a union by voting. Sometimes employers simply agree to recognize a union when most workers sign cards. This bill bans that shortcut and requires a private secret-ballot election every time. Supporters say this protects workers from peer pressure, while unions say the extra time lets companies campaign hard against them.',
  { slot: ['unionvote'], sys: ['unions'] }),
P('unionfin', 'Labor', 2, [0, 0, 0, 0, -1, 1], 0.5, ['labor', 0.3], ['MI', 'WI', 'OH', 'NV'], -1,
  'Require workers to opt in before union dues fund politics',
  'With right-to-work in place, unions must also get yearly written consent before spending dues on campaigns.',
  'Union halls print consent forms. Campaign ads get slightly shorter.',
  ['New Paperwork Rule Aims to Silence Unions at Election Time', 'Workers Finally Choose Whether Dues Fund Political Campaigns'],
  'Under the Supreme Court’s 1988 Beck decision, private-sector workers can object to paying for a union’s political activities, but they must opt out. Some states have tried opt-in rules, sometimes called paycheck protection.',
  'Workers decide for themselves whether their money backs political causes.', 'Paperwork burdens weaken unions while corporations face no similar rule.',
  'Unions collect dues from members and spend some of that money on politics, like supporting candidates. Today workers who disagree have to ask to opt out. After right-to-work passed, this bill flips it: unions must get each worker’s written yes every year before using dues for politics. Workers get more control, but unions say it is designed to weaken their voice.',
  { req: ['rtw'], dl: 2, sys: ['unions'] }),
// ------------------------------------------------------------------ LABOR: benefits and work rules
P('paidleave', 'Labor', -2, [0.1, -0.1, 0.1, 0.1, 4, -1], 0.6, ['business', 0.15], ['CA', 'NJ', 'NY', 'WA', 'MA'], 3,
  'Create 12 weeks of national paid family and medical leave',
  'New parents and workers caring for a sick relative get paid leave, funded by a small payroll tax.',
  'Newborns everywhere celebrate by not sleeping, now with paid leave.',
  ['America Finally Joins the Rest of the Rich World on Paid Leave', 'New Payroll Tax Funds Leave Program Small Businesses Must Juggle'],
  'The US is the only rich OECD country without national paid parental leave. The 1993 FMLA guarantees up to 12 weeks of unpaid leave to eligible workers; California started the first state paid family leave program in 2004.',
  'Keeps parents, especially mothers, attached to their jobs and helps families.', 'New payroll tax, and small firms must cover for absent workers.',
  'Right now federal law only promises some workers unpaid time off after a baby arrives or when a family member is very sick. This bill pays workers part of their wages for up to 12 weeks, funded by a small tax on paychecks. Families get time together without losing income, but everyone pays a little more tax and small businesses must manage while workers are away.'),
P('childcarewf', 'Labor', -2, [0.1, -0.1, 0.1, 0.6, 3, 0], 0.6, null, ['MN', 'MA', 'NM', 'VT'], 2,
  'Fund raises for child care workers to stop staff shortages',
  'With paid leave ending after 12 weeks, parents need child care. This grant raises pay so day cares can hire.',
  'Toddlers report improved staffing ratios and unchanged nap policies.',
  ['Investing in the Workers Who Make All Other Work Possible', 'Washington Steps Into the Day Care Business With Billions'],
  'Child care workers earn among the lowest wages of any occupation, according to BLS data. Temporary federal stabilization grants from the 2021 American Rescue Plan expired in 2023, and many centers reported staffing shortages.',
  'Keeps day cares open so parents, especially mothers, can work.', 'Expensive and does not fix the high price parents still pay.',
  'Paid leave covers the first few months after a baby is born, but then parents need child care to go back to work. Many day cares cannot find enough staff because the pay is very low. This bill gives centers federal money to raise wages. More open spots help parents work, but it costs taxpayers a lot and does not make child care cheap by itself.',
  { req: ['paidleave'], dl: 3 }),
P('sickleave', 'Labor', -1, [-0.05, 0, 0.1, 0, 3, 0], 0.5, ['business', 0.2], ['TX', 'FL', 'GA', 'OH'], 2,
  'Guarantee seven paid sick days a year for every worker',
  'Every employer must give workers at least seven paid sick days. Coughing at the register is no longer a career requirement.',
  'Line cooks stay home with the flu. Customers celebrate quietly.',
  ['Millions of Workers No Longer Have to Choose Between Pay and Health', 'Federal Sick Day Mandate Hits Small Shops Hardest'],
  'BLS data show roughly one in five private-sector workers lacks paid sick leave, mostly in low-wage jobs. Connecticut passed the first state paid sick leave law in 2011, and many states and cities have followed.',
  'Sick workers stay home, limiting the spread of illness.', 'Raises labor costs, and some workers may misuse sick days.',
  'Many workers, especially in restaurants and stores, lose a day’s pay if they call in sick, so they often come to work ill and spread germs. This bill requires every employer to give at least seven paid sick days a year. Public health improves and workers are protected, but businesses pay more and must cover shifts on short notice.'),
P('noncompete', 'Labor', 0, [0.2, -0.1, 0.05, 0, 1, 0], 0.6, ['business', 0.15], ['FL', 'MA', 'TX', 'CO'], 2,
  'Ban most noncompete agreements',
  'Your old boss can no longer stop you from taking a better job across the street.',
  'Sandwich shop workers learn they are free to make sandwiches anywhere.',
  ['Workers Freed to Switch Jobs for Better Pay', 'Ban on Noncompetes Puts Trade Secrets and Training at Risk'],
  'The FTC estimated about one in five workers is bound by a noncompete; its 2024 rule banning most of them was blocked by a federal court. California has long refused to enforce noncompetes and is home to a huge tech industry, though researchers debate how much one explains the other.',
  'More job mobility, more startups and higher wages through competition.', 'Firms may invest less in training workers or sharing secrets.',
  'A noncompete is a contract that stops you from working for a rival company or starting your own for a while after you quit. They are used for executives but also for hair stylists and fast-food workers. This bill bans most of them. Workers can chase better pay, but companies worry rivals will poach their trained workers and secrets.'),
P('gigwork', 'Labor', -2, [-0.2, 0.2, 0.2, -0.1, 0, 1], 0.6, ['business', 0.35], ['CA', 'WA', 'NY', 'IL'], 1,
  'Classify gig drivers and couriers as employees',
  'App drivers become employees under a strict ABC test, with minimum wage, overtime and unemployment insurance.',
  'Ride-share apps discover HR. HR discovers ride-share apps.',
  ['Gig Workers Finally Get the Protections Every Employee Deserves', 'Gig Ban by Another Name: Drivers Lose Their Flexibility'],
  'California’s 2019 AB5 law adopted the ABC test for employee status, but voters in 2020 passed Proposition 22 exempting app-based drivers. Surveys show many drivers value flexible hours, while others rely on gig work full-time.',
  'Gives full-time gig workers wage floors and a safety net.', 'Higher costs mean fewer gigs, higher fares and less schedule freedom.',
  'Drivers for ride-share and delivery apps are usually treated as independent contractors, like freelancers, so they do not get minimum wage or benefits. This bill makes companies treat them as employees. Workers gain protections and pay into unemployment insurance, but apps may raise prices, cut drivers and set shifts instead of letting people log on whenever they want.',
  { slot: ['gigstatus'] }),
P('portben', 'Labor', 1, [0.1, 0, 0, 0.05, 0, 0], 0.5, ['labor', 0.15], ['CA', 'TX', 'FL', 'AZ'], 1,
  'Create portable benefit accounts for independent contractors',
  'After the employee bill was vetoed, a middle path: gig apps pay into benefit accounts that follow the worker.',
  'Drivers get a health stipend. Apps get to keep calling them partners.',
  ['Gig Companies Keep Contractor Status While Benefits Fall Short of Employee Pay', 'Flexible Work With Benefits: A Smart Deal for Gig Workers'],
  'California’s Proposition 22 (2020) kept app drivers as contractors while requiring some benefits, such as a health stipend for drivers with enough hours. Portable benefit accounts have been proposed by both parties in Congress.',
  'Keeps flexibility while giving gig workers a basic safety net.', 'Benefits are thinner than employees get, and it locks in contractor status.',
  'You vetoed making gig workers employees. This bill takes another path: they stay independent contractors, but the apps must put money into a personal benefit account for each worker based on hours driven. The account goes with the worker from app to app. Workers keep their flexibility and get some help with health care or retirement, but less than real employees get.',
  { req: ['~gigwork'], dl: 2, slot: ['gigstatus'] }),
P('uireform', 'Labor', -1, [0, 0, 0.05, 0.4, 2, -1], 0.5, ['business', 0.1], ['MI', 'NV', 'OH', 'FL'], 2,
  'Set national minimum standards for unemployment insurance',
  'Every state must pay at least half of lost wages for at least 26 weeks, and freelancers can join.',
  'Laid-off workers get checks that cover more than a week of groceries.',
  ['Laid-Off Workers Get a Real Safety Net in Every State', 'Federal Takeover of Jobless Benefits May Slow the Return to Work'],
  'Unemployment insurance is a joint federal-state system, and benefit levels and durations vary widely by state. During COVID, Congress temporarily extended aid to gig workers through Pandemic Unemployment Assistance.',
  'Steadier incomes in recessions keep spending up and families afloat.', 'Bigger, longer benefits can delay job searches and raise employer taxes.',
  'When people lose their job through no fault of their own, unemployment insurance pays part of their old wages for a while. Each state sets its own rules, so some states pay much less and for fewer weeks than others. This bill sets a national minimum. Laid-off workers get more help everywhere, but it costs more and some may take longer to find new jobs.'),
P('overtime', 'Labor', -1, [-0.1, 0, 0.1, 0, 2, 0], 0.5, ['business', 0.25], ['TX', 'OH', 'PA', 'NC'], 2,
  'Raise the salary threshold for overtime pay',
  'Salaried "managers" earning under about $60,000 now get time-and-a-half after 40 hours.',
  'Assistant managers discover the word "overtime." Spreadsheets discover them.',
  ['Millions of Salaried Workers Will Finally Be Paid for Extra Hours', 'Overtime Rule Will Turn Salaried Jobs Into Hourly Ones'],
  'Salaried employees earning below a set pay threshold must get overtime. A 2024 Labor Department rule raising the threshold to about $58,000 was struck down by a federal court in Texas, leaving it near $35,000.',
  'Pays workers for long hours or pushes firms to hire more people.', 'Firms may cut base pay or turn salaried staff into hourly workers.',
  'Hourly workers get extra pay, called overtime, for hours past 40 a week. Salaried workers only get it if they earn below a certain yearly amount. This bill raises that amount, so many more people qualify. Workers who put in long hours get paid more, but some companies may cut hours, lower base pay or switch staff to hourly to avoid the cost.',
  { req: ['!otoptout'], slot: ['otrule'] }),
P('taa', 'Labor', -1, [0, -0.1, 0, 0.2, 2, -1], 0.5, null, ['MI', 'OH', 'PA', 'NC'], 2,
  'Revive Trade Adjustment Assistance for workers hurt by imports',
  'Lower tariffs mean cheaper goods and some closed factories. Laid-off workers get retraining, wage insurance and moving help.',
  'Laid-off factory workers get a textbook. Some of them even open it.',
  ['Help for Workers Left Behind by Trade Deals', 'Another Federal Program With a Shaky Track Record'],
  'Trade Adjustment Assistance has helped workers displaced by imports since 1962, but its authorization lapsed in 2022. Studies of its results are mixed: training helped some workers, while many never regained their old wages.',
  'Spreads the gains from trade to the workers who lose from it.', 'Results are mixed, and it singles out trade over other causes of job loss.',
  'Open trade makes many products cheaper, but some factories cannot compete with imports and close. Trade Adjustment Assistance pays for laid-off workers to retrain, move to new jobs, or get a top-up if their new job pays less. It helps the people hurt most by trade, but studies disagree on how well it works.',
  { req: [['trade', 'freetrade', 'pacpact']], dl: 3 }),
P('jobtrain', 'Labor', -1, [0.1, -0.1, 0, 0.3, 2, 0], 0.5, null, ['IN', 'OH', 'KY', 'TN'], 2,
  'Give every worker a lifelong learning account for job training',
  'Trade aid only helps workers who lost jobs to imports. This gives every worker a training account, whatever cost them their job.',
  'Robots, imports and bad bosses are now equally covered.',
  ['Every Worker Gets a Shot at New Skills', 'Federal Training Programs Have a Long History of Disappointing'],
  'Results of federal job training are mixed overall, but randomized trials of sector-focused programs such as Year Up and Project QUEST found sizable earnings gains for participants.',
  'Helps workers keep up as technology and trade change jobs.', 'Many training programs have weak results; money may go to low-quality providers.',
  'Trade Adjustment Assistance only helps people who lost jobs to imports. This bill gives every worker an account they can spend on approved training, like coding, welding or nursing classes, no matter why their job disappeared. Workers can learn new skills, but past training programs have had uneven results and some schools may take the money without delivering.',
  { req: ['taa'], dl: 2 }),
P('apprentice', 'Labor', 1, [0.05, -0.05, 0, 0, 0, 1], 0.5, ['labor', 0.1], ['WI', 'SC', 'IN', 'GA'], 2,
  'Let industry groups certify apprenticeships that training accounts can pay for',
  'Training accounts may now pay for apprenticeships approved by industry groups, not only ones registered by the Labor Department.',
  'Teens learn welding. Parents learn the phrase "earn while you learn."',
  ['Industry-Run Apprenticeships Risk Weaker Standards for Trainees', 'Employers, Not Bureaucrats, Decide Which Skills Count'],
  'Registered apprenticeships, approved by the Labor Department or state agencies, cover a small share of US workers compared with Germany or Switzerland. A Trump-era Labor Department effort to let industry groups certify apprenticeships was ended by the next administration.',
  'More apprenticeship slots, faster, shaped by the skills employers need.', 'Weaker oversight could mean low-quality programs or cheap labor called training.',
  'An apprenticeship is a paid job where you learn a trade, like electrical work or machining, from experienced workers. Today the government approves each official program, which can be slow. This bill lets trusted industry groups approve them too, and workers can spend their new training accounts on them. More programs could open quickly, but critics worry quality and safety standards could slip.',
  { req: ['jobtrain'], dl: 2 }),
// ------------------------------------------------------------------ HOUSING
P('supplyfund', 'Housing', -1, [0.2, -0.1, -0.1, 0.5, 1, 0], 0.6, null, ['CA', 'CO', 'TX', 'AZ'], 2,
  'Create a housing supply fund for cities that add homes',
  'Zoning now allows apartments, but new homes need pipes and roads. Cities that permit the most get federal infrastructure money.',
  'Mayors compete to build. The prize is a sewer line.',
  ['Federal Money Rewards Cities That Build Homes', 'Washington Bribes Towns to Build What It Already Ordered'],
  'Estimates of the US housing shortage range from a few million to several million homes, depending on the method. New housing often stalls on the cost of water, sewer and road upgrades.',
  'Helps cities pay for the pipes and roads that new housing needs.', 'Costs federal money and rewards cities for building they might do anyway.',
  'After the zoning override, builders may put up apartments where they were once banned. But new homes need water pipes, sewers and roads, and cities often cannot afford them. This fund gives federal money to cities that approve lots of new homes. More homes could get built faster, but it costs taxpayers and some cities might have built anyway.',
  { req: ['zone'], dl: 2 }),
P('impactfee', 'Housing', 1, [0.1, 0, -0.1, 0, 0, 1], 0.5, null, ['CA', 'CO', 'FL', 'WA'], 1,
  'Cap local impact fees on new homes for supply-fund cities',
  'Cities taking supply-fund money may not charge builders more than a modest fee per new home.',
  'Builders stop paying $40,000 for a permit. Permit offices stop smiling.',
  ['Cap on Builder Fees Shifts Costs From Developers to Towns', 'Cheaper Permits Mean Cheaper Homes for First-Time Buyers'],
  'Impact fees charge builders for the public services new homes use. A UC Berkeley Terner Center study found fees in some California cities reach tens of thousands of dollars per home.',
  'Lowers the cost of building, which helps lower home prices.', 'Towns lose money for schools, parks and roads that new residents use.',
  'Many towns charge builders a fee, called an impact fee, for every new home to pay for schools, parks and roads. In some places it can be tens of thousands of dollars, which raises home prices. This bill says cities getting supply-fund money must cap these fees. Homes get cheaper to build, but towns must find other ways to pay for services.',
  { req: ['supplyfund'], dl: 2 }),
P('modular', 'Housing', 1, [0.1, 0, -0.1, 0, 0, 1], 0.5, null, ['IN', 'PA', 'GA', 'TX'], 1,
  'Create one national building code for factory-built homes',
  'With supply-fund money flowing, a home built in a factory is approved once and accepted in every state.',
  'Houses now arrive on a truck. Neighbors watch like it is a parade.',
  ['Factory Homes Could Cut Costs, but Local Safety Rules Are Overridden', 'One Code, Many Homes: Factory Building Gets Its Big Break'],
  'Mobile homes have followed a single national HUD code since 1976, but modular homes must meet differing state and local codes. Factory building can cut waste and build time, though transport and setup add cost.',
  'Factory homes can be built faster and cheaper at scale.', 'Overrides local building rules suited to local climate and safety.',
  'Some homes are built in factories in sections and then trucked to the lot, which can be faster and cheaper. But each state or town may have different building rules, so factories cannot build one design for everyone. Now that the supply fund pays for new housing, this bill creates one national standard. Building could get cheaper, but local governments lose control over safety rules.',
  { req: ['supplyfund'], dl: 2 }),
P('parkmin', 'Housing', 1, [0.1, 0, -0.05, 0, -1, 0], 0.5, null, ['CA', 'OR', 'MN', 'TX'], 1,
  'End mandatory parking minimums for new housing',
  'The zoning override allows apartments, but many local codes still require parking spots for every unit, whether residents own cars or not.',
  'A two-bedroom apartment no longer requires two spots and a ramp.',
  ['Homes Not Garages: Parking Rules Finally Ease', 'Ending Parking Rules Means Circling the Block Forever'],
  'Buffalo became the first major US city to drop minimum parking requirements citywide in 2017, and Minneapolis followed in 2021. Structured parking can add tens of thousands of dollars to the cost of each apartment.',
  'Lowers building costs and frees land for homes.', 'More cars on the street and harder parking for neighbors.',
  'Many cities require builders to provide a set number of parking spaces with every new home or apartment, even if residents do not drive. Parking takes up land and costs a lot to build. After the big zoning change, this bill ends those requirements. Builders could fit more homes and charge less, but neighbors worry about crowded streets.',
  { req: ['zone'], dl: 2 }),
P('tenantaid', 'Housing', -2, [0, 0, 0, 0.3, 3, -1], 0.5, null, ['NY', 'CA', 'GA', 'FL'], 2,
  'Fund emergency rental assistance to prevent evictions',
  'Whatever happened with rent control, renters who fall behind can now get one-time help before an eviction.',
  'Landlords get paid. Tenants keep their couches on the inside.',
  ['Emergency Help Keeps Families in Their Homes', 'Rent Bailout Program Invites Fraud and Delays Real Fixes'],
  'During COVID, Congress funded about $46 billion in Emergency Rental Assistance. Studies linked it to fewer evictions, though money reached tenants slowly at first and some programs faced fraud.',
  'Preventing evictions avoids homelessness, school disruption and costlier help later.', 'Costs money, can be slow and does nothing to lower rents.',
  'After the national debate over rent control, many renters still fall behind after a job loss or medical bill. Getting evicted can mean losing a home, moving schools and struggling to rent again. This fund pays back rent directly to landlords for tenants in crisis. It keeps families housed, but it costs taxpayers and does not make rent cheaper.',
  { req: [['rc', 'endrc', '~rc']], dl: 2 }),
P('housevoucher', 'Housing', -2, [0.1, 0, 0.1, 0.8, 3, -1], 0.6, null, ['CA', 'NY', 'TX', 'FL', 'GA'], 3,
  'Make housing vouchers available to every low-income family',
  'Emergency aid is one-time. This bill turns Section 8 vouchers into a guarantee for every eligible household.',
  'Waiting lists that last a decade are replaced by a form that lasts a week.',
  ['Housing Help for Every Family That Qualifies, Not Just the Lucky Ones', 'Huge New Entitlement Could Push Up Rents Everywhere'],
  'Only about one in four households eligible for federal rental assistance receives it, according to the Center on Budget and Policy Priorities. Vouchers reduce homelessness, but when housing is scarce they can push up rents.',
  'Cuts homelessness and gives families stable homes.', 'Very expensive, and rents may rise if new supply does not follow.',
  'Housing vouchers, often called Section 8, pay part of a low-income family’s rent. Today they are like a lottery: most families who qualify never get one. After the emergency rental fund, this bill makes vouchers available to every family that qualifies. Fewer people would be homeless, but it costs a lot and may raise rents if there are not enough homes.',
  { req: ['tenantaid'], dl: 3 }),
P('srcincome', 'Housing', -1, [0, 0, 0.05, 0, 1, 0], 0.5, ['business', 0.1], ['TX', 'GA', 'FL', 'AZ'], 1,
  'Ban landlords from rejecting tenants for using vouchers',
  'Universal vouchers only work if landlords accept them. Now "No Section 8" ads are illegal.',
  'Rental listings lose a familiar phrase. Landlords lose an excuse.',
  ['Voucher Families Can Finally Rent Where They Choose', 'New Mandate Forces Landlords Into Federal Paperwork'],
  'Many states and cities already ban source-of-income discrimination against voucher holders. Some research finds these laws help voucher holders find a unit, though the effects are modest and enforcement varies.',
  'Lets voucher families move to safer neighborhoods with better schools.', 'Landlords face inspections, paperwork and payment delays they did not choose.',
  'With vouchers now available to every eligible family, there is a catch: many landlords refuse to rent to anyone using one. This bill makes that illegal. Families with vouchers could live in more neighborhoods, including ones with good schools, but landlords dislike the extra inspections, paperwork and slow payments from housing agencies.',
  { req: ['housevoucher'], dl: 2 }),
P('lihtc', 'Housing', -1, [0.1, 0, 0, 0.2, 1, 0], 0.5, null, ['CA', 'NY', 'TX', 'WA'], 1,
  'Expand the Low-Income Housing Tax Credit by 50%',
  'Investors who fund affordable apartments get more tax credits, so more affordable apartments get built.',
  'Affordable housing gets financed. Tax lawyers get billable hours.',
  ['More Affordable Apartments Are on the Way', 'Tax Credit Expansion Pays Middlemen More Than Renters'],
  'Created in 1986, the Low-Income Housing Tax Credit is the largest federal program for building affordable rental housing. Critics note that some of the subsidy goes to fees and financing costs.',
  'Builds affordable homes that stay affordable for decades.', 'Costly per apartment, with much of the money going to middlemen.',
  'The Low-Income Housing Tax Credit gives tax breaks to investors who pay to build apartments with lower rents for low-income families. This bill gives out 50% more of these credits. More affordable apartments would be built, but each one costs a lot and some of the money goes to lawyers, banks and developers instead of tenants.',
  { sys: ['inctax', 'deduct'] }),
P('firsthome', 'Housing', -1, [0.1, 0, 0.2, 0.5, 3, 0], 0.5, null, ['AZ', 'NV', 'GA', 'NC', 'PA'], 3,
  'Give first-time homebuyers $25,000 for a down payment',
  'First-time buyers get a federal grant toward their down payment. Sellers have been informed.',
  'Starter homes get starter money. Sellers raise the starter price.',
  ['Young Families Get a Foot in the Door of Homeownership', 'Down Payment Handout Will Just Push Up Home Prices'],
  'Economists widely warn that demand subsidies for homebuyers, without more housing supply, tend to push up prices and partly flow to sellers. Saving for a down payment is a common barrier for young buyers.',
  'Helps renters build wealth by owning a home.', 'Raises home prices if supply stays tight, partly helping sellers instead.',
  'Saving enough for a down payment is one of the hardest parts of buying a first home. This bill gives first-time buyers up to $25,000 from the government. More young families could buy a house, but if the number of homes for sale does not grow, more buyers with more money could just push prices up.'),
// ------------------------------------------------------------------ TRANSPORT
P('transitfund', 'Transport', -1, [0.1, 0, 0, 0.3, 1, 0], 0.5, null, ['NY', 'CA', 'WA', 'IL', 'VA'], 1,
  'Fund transit lines in cities that allow homes near stations',
  'Federal transit grants go first to cities that zone for apartments within walking distance of stops.',
  'New train lines arrive with neighbors, not just parking lots.',
  ['Transit and Housing Finally Planned Together', 'Federal Strings Attached to Local Transit Money'],
  'Research finds that more homes near frequent transit raise ridership and lower driving. Federal transit grants weigh local land use, but do not require cities to allow housing near stations.',
  'Gets more riders and more homes out of each transit dollar.', 'Federal strings on local land use, and big-city projects cost a lot.',
  'Building a train or bus line is expensive, and it works best when lots of people live nearby. This bill gives federal transit money first to cities that allow apartments close to stations. More people could live without long car commutes, but it costs money and some towns dislike Washington telling them how to plan neighborhoods.'),
P('portinfra', 'Transport', -1, [0.2, -0.1, -0.1, 0.4, 1, 0], 0.5, null, ['CA', 'WA', 'GA', 'TX', 'NJ'], 2,
  'Fund port and freight rail upgrades to clear supply-chain jams',
  'Cranes, rail links and truck lanes for the ports where goods pile up.',
  'Container ships stop parking off the coast like cars at a drive-in.',
  ['Port Upgrades Promise Fewer Shortages and Lower Prices', 'Billions for Ports, With No Promise They Get Faster'],
  'In 2021, dozens of container ships waited offshore at the ports of Los Angeles and Long Beach, helping delay goods and push up prices. US ports also lag top Asian and European ports in automation.',
  'Faster shipping lowers costs and makes shortages less likely.', 'Costs money, and ports may need labor and work-rule changes to benefit.',
  'Most of the goods Americans buy from abroad arrive in big metal containers at a few busy ports. When ports get jammed, ships wait for weeks and stores run short. This bill pays for bigger cranes, rail links and roads at ports. Goods could move faster and prices could ease, but it costs taxpayers and only helps if ports run efficiently.'),
P('jonesact', 'Transport', 2, [0.1, 0, -0.1, 0, 0, 1], 0.5, ['labor', 0.3], ['LA', 'VA', 'MS', 'WA'], -2,
  'Repeal the Jones Act limits on shipping between US ports',
  'Foreign-built ships may now carry cargo between US ports, from Texas oil to Hawaiian groceries.',
  'Groceries reach Hawaii by any ship that floats. Gulf Coast shipyards are not amused.',
  ['Shipyard Jobs Sacrificed for Cheaper Foreign Shipping', 'A Century-Old Rule Ends; Hawaii and Puerto Rico Pay Less'],
  'The 1920 Jones Act requires cargo moving between US ports to travel on ships that are US-built, owned and crewed. Economists generally find it raises shipping costs, especially for Hawaii, Alaska and Puerto Rico.',
  'Cheaper shipping between US ports, especially for islands.', 'Hurts US shipyards and mariners that the military may need in war.',
  'A law from 1920 says only American-built, American-owned ships with American crews can carry goods from one US port to another. That protects shipyards and sailors, but American ships cost much more, so shipping to places like Hawaii is expensive. Repealing the law could lower prices, but US shipbuilding jobs and military readiness could suffer.'),
// ------------------------------------------------------------------ TRADE
P('targettariff', 'Trade', -1, [-0.1, 0, 0.2, -0.1, 1, 0], 0.6, ['farmers', 0.15], ['OH', 'PA', 'MI', 'IN'], 2,
  'Put targeted tariffs on Chinese steel, EVs and chips only',
  'After the 25% tariff on everything was vetoed, a narrower version hits only strategic goods from China.',
  'Tariffs trade the sledgehammer for a scalpel. The scalpel is still a tariff.',
  ['Narrow Tariffs Still Tax American Buyers', 'Smart Tariffs Protect Key Industries Without a Trade War'],
  'The US placed Section 301 tariffs on many Chinese goods in 2018, and in 2024 raised the tariff on Chinese electric vehicles to 100%. Studies found US buyers paid most of the 2018 tariff costs, and China retaliated against US farm exports.',
  'Protects strategic industries without taxing every import.', 'Raises prices for US buyers and invites retaliation against farmers.',
  'You vetoed a 25% tariff on all imports. This bill instead taxes only a few products from China that matter for national security and key industries, like steel, electric cars and computer chips. It shields those American industries at a lower cost than a broad tariff, but buyers still pay more and China may hit back by refusing American crops.',
  { req: ['~tar25'], dl: 2, slot: ['tariffs'] }),
P('buyamerica', 'Trade', -1, [0, 0, 0.05, 0.2, 2, 0], 0.5, null, ['OH', 'PA', 'MI', 'WI'], 2,
  'Tighten Buy American rules for federal purchases',
  'Federal agencies and highway projects must buy goods with at least 75% American-made content.',
  'The Pentagon’s new staplers are proudly made in Ohio. They cost $90.',
  ['Tax Dollars Will Support American Factories and Workers', 'Buy American Rules Mean Costlier Bridges and Fewer of Them'],
  'The Buy American Act dates to 1933, and recent rules have raised the domestic-content share required in federal purchases. Studies find such rules raise procurement costs, with debated effects on jobs.',
  'Keeps taxpayer money supporting American factories.', 'Costs taxpayers more, so each dollar builds less.',
  'The federal government buys huge amounts of stuff, from trucks to steel for bridges. This bill requires that more of what it buys be made in the USA. American factories and workers get more business, but American-made goods often cost more, so taxpayers pay more and each project might build less.'),
P('chips', 'Trade', -1, [0.2, -0.1, 0, 0.4, 1, 0], 0.6, null, ['AZ', 'OH', 'NY', 'TX', 'OR'], 2,
  'Add $50 billion more in subsidies for US chip factories',
  'A second round of grants for semiconductor plants, so fewer of the world’s chips depend on one island.',
  'Arizona’s newest desert crop is the microchip, watered with federal money.',
  ['New Chip Funding Brings High-Tech Jobs Home', 'Billions in Subsidies for Chipmakers That Could Fund Their Own Factories'],
  'The 2022 CHIPS and Science Act provided about $52 billion for US semiconductor manufacturing and research. Most of the world’s most advanced chips are made in Taiwan, which many see as a security risk.',
  'Secures a vital supply chain and builds high-tech jobs.', 'Expensive subsidies to rich companies; government picks winners.',
  'Computer chips power everything from phones to cars to missiles, and most advanced ones are made in Taiwan. This bill gives chip companies another $50 billion in grants to build factories in the US. It could make the country safer from supply shocks and create jobs, but it costs a lot and sends money to very profitable companies.'),
P('pacpact', 'Trade', 2, [0.2, 0, -0.1, 0, -1, 1], 0.6, ['labor', 0.2], ['WA', 'OR', 'IA', 'CA'], 2,
  'Join the Pacific trade pact (CPTPP)',
  'The US applies to join the Pacific trade bloc that grew out of the deal it helped design and then left.',
  'America joins the Pacific club. The membership fee is opening its own market a little wider.',
  ['Pacific Pact Puts Corporate Profits Ahead of Factory Jobs', 'Pacific Deal Opens Markets and Counters China'],
  'The US withdrew from the Trans-Pacific Partnership in 2017; the other 11 countries signed the CPTPP in 2018, and the UK joined in 2024. Economists expect modest overall gains, larger for exporters and farmers.',
  'Opens markets for US farmers and firms and builds an alliance against China.', 'Exposes some factory workers to more competition and limits national rules.',
  'The CPTPP is a trade agreement among countries around the Pacific, like Japan, Canada and Australia. Members lower tariffs and agree on trade rules. The US helped write it, then left in 2017. Joining would help American farmers and exporters sell abroad and stand together against China, but some factory workers could face more competition.',
  { slot: ['tariffs'] }),
// ------------------------------------------------------------------ FARM
P('farmaid', 'Farm', -1, [0, 0, 0, 0.6, 2, -1], 0.5, null, ['IA', 'NE', 'KS', 'ND', 'MN'], 4,
  'Send emergency payments to farmers hit by trade retaliation',
  'The new tariffs sparked foreign retaliation against American crops. Farmers get checks to make up the lost sales.',
  'Soybeans pile up in I-owe-a. So do the federal checks.',
  ['Farmers Bailed Out From a Trade War They Did Not Start', 'Farm Bailout Proves the Tariffs Cost More Than Promised'],
  'In 2018 and 2019, after China retaliated against US tariffs, USDA’s Market Facilitation Program paid farmers about $23 billion. Studies found the payments went disproportionately to larger farms.',
  'Keeps family farms afloat when they become trade-war casualties.', 'Costs billions, favors big farms, and hides the true cost of tariffs.',
  'When the US raised tariffs, other countries struck back by refusing or taxing American crops like soybeans and pork. Farmers lost customers through no fault of their own. This bill pays them to cover the losses. It keeps farms in business, but it costs taxpayers billions, often helps the biggest farms most, and shows that tariffs have hidden costs.',
  { req: [['tar25', 'tariff40', 'targettariff'], '!farmsub'], dl: 3, slot: ['farmpay'] }),
P('farmsub', 'Farm', 2, [0, 0, 0, -0.2, -2, 2], 0.6, ['farmers', 0.45], ['IA', 'NE', 'KS', 'ND', 'MN'], -4,
  'Phase out federal crop subsidy payments over ten years',
  'Corn, wheat and cotton price supports wind down. Farmers will be paid by customers, like everyone else.',
  'Cornbraska reconsiders its relationship with Washington.',
  ['Farm Families Lose Their Safety Net in Volatile Markets', 'End of Farm Welfare Saves Billions and Frees Markets'],
  'USDA data show commodity payments flow disproportionately to larger farms. New Zealand scrapped most farm subsidies in the mid-1980s; after a hard transition, its farm sector grew more productive.',
  'Saves money and stops subsidizing big agribusiness.', 'Farming is risky; small farms could fold after one bad season.',
  'The government pays farmers who grow crops like corn, wheat and cotton when prices or revenues drop. This bill slowly ends those payments over ten years. Taxpayers save money and fewer subsidies go to giant farms, but farming is risky because of weather and prices, and some smaller family farms might not survive a bad year.',
  { slot: ['farmprog', 'farmpay'] }),
P('cropins', 'Farm', -1, [0, 0, 0, 0.2, 1, 0], 0.5, null, ['IA', 'NE', 'ND', 'KS', 'SD'], 3,
  'Expand subsidized crop insurance for smaller farms',
  'You kept farm subsidies, so their backers want more: richer crop insurance subsidies aimed at smaller farms.',
  'Drought insurance gets cheaper. The drought does not.',
  ['Small Farms Get Better Protection From Disaster', 'Taxpayers Pay More to Insure Risks Farmers Choose to Take'],
  'Taxpayers cover on average about 60% of federal crop insurance premiums. Crop insurance has become the largest part of the farm safety net, and its benefits grow with the size of the farm.',
  'Protects small farms from ruin after floods, droughts and price crashes.', 'More taxpayer cost and encourages planting on risky land.',
  'Crop insurance pays farmers when floods, droughts or low prices wipe out their harvest. The government already pays most of the cost. After you vetoed ending farm subsidies, this bill makes the insurance cheaper still for smaller farms. Family farms get more protection, but taxpayers pay more and farmers may plant on land that floods often.',
  { req: ['~farmsub'], dl: 2, slot: ['farmprog'] }),
P('repair', 'Farm', 0, [-0.05, 0, -0.05, 0, 2, 0], 0.5, ['business', 0.15], ['IA', 'NE', 'MT', 'ND', 'CO'], 3,
  'Give farmers and consumers a right to repair their equipment',
  'Makers of tractors, phones and appliances must sell parts, tools and manuals to owners and independent shops.',
  'Farmers fix their own tractors. The tractors have opinions about it.',
  ['Right to Repair Breaks Corporate Lock on Your Own Stuff', 'Farmers and Consumers Win the Freedom to Fix What They Own'],
  'Colorado passed the first state right-to-repair law for farm equipment in 2023. A 2021 FTC report found little evidence to support many manufacturer repair restrictions.',
  'Lower repair costs, less waste and more competition for repairs.', 'Manufacturers warn of safety, security and emissions-tampering risks.',
  'Many modern machines, from tractors to phones, use software and special parts that only the maker can fix. Farmers sometimes wait days for a dealer during harvest. This bill requires companies to sell parts, tools and repair guides to owners and independent shops. Repairs get cheaper and faster, but companies worry about safety and people tampering with emissions controls.'),
];
