import { P } from './p.js';
export const TAX_FIN = [
// ------------------------------------------------------------------ TAXES
P('stdded', 'Taxes', 1, [0.2, -0.1, 0.1, 0.8, 3, 0], 0.6, null, ['TX', 'OH', 'GA'], 2,
  'Double the standard deduction',
  'Most families already skip itemizing. Now the tax-free first slice of their income doubles in size.',
  'Shoeboxes of receipts retire to the attic. Tax-prep software sulks quietly in the cloud.',
  ['Middle-Class Tax Cut Passes, but Nobody Says Who Pays for It', 'Simpler Taxes: Millions More Families Will Never Itemize Again'],
  'The 2017 tax law nearly doubled the standard deduction, and the share of filers who itemize fell from about 30 percent to roughly one in ten.',
  'A simple tax cut that reaches nearly every working family.',
  'Costs a lot of revenue and shrinks the tax base, so rates may have to rise later.',
  'The standard deduction is the amount of income you can earn before income tax applies, unless you list your deductions one by one. Doubling it cuts taxes for most families and makes filing simpler. The catch is that the government collects much less money, which adds to the deficit unless spending is cut.',
  { slot: ['stdded'], sys: ['inctax', 'deduct'] }),
P('mortded', 'Taxes', -1, [-0.05, 0, 0, 0, 1, 0], 0.5, ['business', 0.1], ['CA', 'NJ', 'MD'], -1,
  'Replace the mortgage interest deduction with a flat 15% homeowner credit',
  'With the standard deduction doubled, few families itemize, so the old break mostly helps big mortgages. A credit gives every owner the same rate.',
  'Realtors redo their sales pitches. First-time buyers check their math twice and smile.',
  ['Homeowner Break Finally Reaches Families, Not Just Mansions', 'Coastal Homeowners Lose a Deduction They Planned Their Lives Around'],
  'With a large standard deduction, few middle-income owners itemize, so the mortgage interest deduction mainly benefits higher earners. Most economists find it does little to raise homeownership and partly pushes up home prices.',
  'Spreads the homeowner break evenly instead of rewarding the biggest mortgages.',
  'Owners of expensive homes lose a break they counted on, which could cool some housing markets.',
  'Homeowners who list deductions can subtract mortgage interest from their taxable income, which helps people with big loans and high incomes the most. This bill swaps it for a credit worth 15% of the interest paid, the same rate for every owner. Middle-income owners gain, while owners of costly homes in places like California lose part of their break.',
  { req: ['stdded'], slot: ['mortded'], sys: ['inctax', 'deduct'] }),
P('charity', 'Taxes', 1, [0, 0, 0, 0.2, 2, 0], 0.5, null, ['UT', 'TN', 'MN'], 2,
  'Expand the charitable deduction for people who do not itemize',
  'With the standard deduction doubled, charities warn donors lost their tax reason to give. Now everyone may deduct gifts.',
  'Uplifting Utah food banks report record donations. Tax forms gain a new line nobody reads.',
  ['Charities Get a Lifeline as the Giving Incentive Returns for Everyone', 'Washington Rewards Generosity Without Picking the Causes'],
  'A small deduction for non-itemizers existed in 2020 and 2021, and a 2025 law created a permanent one starting in 2026. Studies find giving responds to tax incentives, though part of the break goes to gifts that would happen anyway.',
  'Encourages giving to food banks, churches and other charities.',
  'Costs revenue, and much of it rewards giving that would have happened anyway.',
  'A charitable deduction lowers your taxes when you give money to a charity. Right now it mostly helps people who itemize, and after the standard deduction doubled, few do. This bill lets everyone deduct gifts. Charities gain donations, but the government collects less, partly for gifts people would have made anyway.',
  { req: ['stdded'], sys: ['inctax', 'deduct'] }),
P('salt', 'Taxes', 1, [0.1, 0, 0, 0.4, 0, 0], 0.5, null, ['NY', 'NJ', 'CA', 'CT'], 3,
  'Remove the cap on the state and local tax (SALT) deduction',
  'Homeowners in high-tax states may once again deduct every dollar of state and property tax.',
  'Newer Jersey property tax bills remain enormous, but now they are enormously deductible.',
  ['SALT Cap Repeal: A Tax Cut Aimed Squarely at Wealthy Suburbs', 'Relief for Overtaxed Families Who Subsidize Low-Tax States'],
  'The 2017 law capped the SALT deduction at $10,000, and a 2025 law raised the cap to $40,000 for most filers for several years. Studies find most of the benefit of removing the cap goes to high-income households.',
  'Stops taxing people on money they already paid in state and local taxes.',
  'Mostly helps high earners and uses federal money to cushion high state taxes.',
  'People who list their deductions can subtract state income and property taxes from the income the federal government taxes, but only up to a cap. Removing the cap cuts taxes mainly for higher earners in high-tax states like New York and California. It costs federal revenue, and critics say it rewards states for taxing more.',
  { slot: ['salt'], sys: ['inctax', 'deduct'] }),
P('progbrk', 'Taxes', -1, [-0.2, 0, 0, -0.3, 2, 0], 0.5, ['business', 0.2], ['NY', 'CA', 'MA'], -1,
  'Add a 5% surtax on income above $1 million',
  'After the 70% top rate was vetoed, a smaller step: an extra 5 cents on each dollar past the first million.',
  'Taxachusetts shrugs, since it already has one. Newer York accountants schedule overtime.',
  ['Millionaire Surtax Asks the Richest to Chip In a Little More', 'Another Bracket on Top: Business Owners Fear They Are Next'],
  'Massachusetts voters approved a 4% surtax on income over $1 million in 2022. Because top incomes swing with markets, revenue from such taxes is volatile, and estimates depend on how much income is shifted or delayed.',
  'Raises revenue from those best able to pay without touching anyone else.',
  'Hits business owners who pay through the personal tax code and invites avoidance.',
  'A surtax is an extra tax added on top of the normal rate. This one applies only to the part of a person’s income above $1 million, so very few people pay it. It raises money from the richest households, but they may find ways to delay or shift income, and some owners of businesses would pay more too.',
  { req: ['~top70'], slot: ['toprate'], sys: ['inctax'] }),
P('taxfree', 'Taxes', 1, [0.1, -0.1, 0.1, 0.5, 3, 0], 0.5, null, ['NV', 'FL', 'HI'], 3,
  'Make tips and overtime pay permanently free of income tax',
  'Servers keep their tips and the night shift keeps its time-and-a-half, untouched by the income tax.',
  'Nevada Vegas waiters celebrate. Accountants quietly explore whether a salary can be called a tip.',
  ['Tip Tax Break Skips Millions of Low-Wage Workers Who Owe No Income Tax', 'Workers Keep What They Earn: Waitresses and Welders Win'],
  'A 2025 law created capped deductions for some tip and overtime income through 2028. Analysts note many tipped workers already owe little income tax, and that pay could be relabeled as tips or overtime to qualify.',
  'Rewards hard work and extra hours, and helps service workers keep more.',
  'Treats people with equal incomes differently, costs revenue and invites gaming.',
  'Tips are money customers give servers and others, and overtime is the extra pay for working more than 40 hours a week. This bill stops charging income tax on both. Workers who rely on them keep more, but people earning the same amount in other ways still pay full tax, and employers could relabel pay to dodge tax.',
  { slot: ['taxfree'], sys: ['inctax'] }),
P('payrollhol', 'Taxes', 1, [0.3, -0.2, 0.1, 0.8, 3, 0], 0.6, ['retirees', 0.15], ['OH', 'MI', 'PA'], 2,
  'Cut the workers’ Social Security payroll tax by 2 points for two years',
  'Every paycheck grows a little, right away. Social Security is promised the money back from general funds.',
  'Ohi-yo! Paychecks rise by a few dollars. Workers notice, spend it, and forget why.',
  ['Paycheck Boost Raids Social Security’s Funding Stream, Advocates Warn', 'Fast Tax Cut Puts Money in Every Worker’s Pocket'],
  'In 2011 and 2012 the employee Social Security tax was cut from 6.2 to 4.2 percent as a recession measure, and general revenue reimbursed the trust funds. When it expired at the end of 2012, paychecks visibly shrank.',
  'Quick stimulus that reaches every worker, including those who owe no income tax.',
  'Adds to the debt and weakens the idea that Social Security pays for itself.',
  'The payroll tax is taken out of every paycheck to pay for Social Security. This bill cuts the worker’s share for two years, so take-home pay rises right away and people spend more. The lost money is replaced from the general budget, which adds to the national debt, and ending the cut later can feel like a tax hike.',
  { slot: ['payrollrate'] }),
P('closeloop', 'Taxes', -1, [-0.05, 0, 0, -0.05, 2, 0], 0.5, ['business', 0.2], ['NY', 'CT', 'MA'], -1,
  'Tax carried interest as ordinary income for investment fund managers',
  'Fund managers’ cut of the profits would be taxed like a salary instead of like an investment gain.',
  'Connecticash hedge fund managers learn the top income tax bracket was there all along.',
  ['Wall Street’s Favorite Loophole Finally Closed', 'Tax Hike on Fund Managers Could Chill Startup Investment'],
  'Private equity and hedge fund managers can often have much of their pay taxed as long-term capital gains. The 2017 law lengthened the holding period to three years instead of ending the break. Revenue estimates are modest compared with the attention it gets.',
  'Taxes pay for managing other people’s money the same as pay for other work.',
  'Raises little money and may discourage investment in new companies.',
  'Investment fund managers often get paid with a share of the fund’s profits, called carried interest. That pay is usually taxed at the lower rate for investment gains, not the higher rate for wages. This bill makes it taxed like a salary. It feels fairer to many people, but raises fairly little money.',
  { slot: ['carried'], sys: ['inctax'] }),
P('profitshift', 'Taxes', -1, [-0.1, 0, 0, -0.15, 1, 0], 0.6, ['business', 0.25], ['DE', 'CA', 'WA'], -1,
  'Tax US multinationals’ offshore profits at a 15% global minimum',
  'With the corporate rate now cut to 15%, profits parked in tax havens must pay at least that much too.',
  'Island shell companies with no employees notice their first tax bill. Delaware lawyers redraw the org charts.',
  ['Corporations Can No Longer Hide Profits on Islands With No Offices', 'Global Tax Rule Gives Foreign Governments a Say Over US Firms'],
  'In 2021 more than 130 countries agreed on a 15% global minimum tax for large multinationals, and many have adopted it. The US did not; it kept its own lower minimum tax on foreign profits, created in 2017. Studies estimate a large share of multinational profits is booked in low-tax countries.',
  'Stops companies from dodging tax by booking profits where they have few workers.',
  'Raises costs for US firms competing abroad and adds complicated rules.',
  'Big companies can move profits on paper to countries with very low taxes, even if their workers and customers are elsewhere. This bill says those offshore profits must be taxed at least 15%, the same as the new US rate. It closes a loophole, but US companies say it makes them less competitive and adds paperwork.',
  { req: ['corp15'], sys: ['corp'] }),
P('exittax', 'Taxes', -2, [-0.05, 0, 0, -0.05, 1, 0], 0.4, null, ['NY', 'CA', 'FL'], 0,
  'Raise the exit tax on wealthy people who renounce citizenship',
  'With new taxes on the very rich, a few may try to leave the country. Those who do pay a steeper toll at the door.',
  'Flori-duh real estate agents note fewer clients relocating to Monaco. Monaco notes the same.',
  ['Billionaires Can’t Dodge Taxes Just by Trading Passports', 'Exit Tax Hike Treats Leaving the Country Like a Crime'],
  'Since 2008, wealthy Americans who give up citizenship are generally taxed as if they sold all their assets the day before. Only a few thousand people renounce each year, so the revenue at stake is small.',
  'Keeps new taxes on the rich from being escaped by moving abroad.',
  'Raises little money and penalizes leaving instead of fixing the tax code.',
  'Americans owe US tax even when they live abroad, unless they give up their citizenship. Some very rich people consider doing that to avoid higher taxes. An exit tax charges them on their gains when they leave. It protects the new taxes, but raises little money and some see it as punishing people for leaving.',
  { req: [['top70', 'top90', 'wealth', 'unrealized', 'progbrk']], dl: 2, sys: ['inctax'] }),
P('unrealized', 'Taxes', -2, [-0.2, 0, 0, -0.4, 2, 0], 0.7, ['business', 0.3], ['CA', 'WA', 'NY'], -1,
  'Tax the yearly investment gains of households worth over $100 million',
  'You vetoed the wealth tax. This narrower version taxes the rise in value of the richest portfolios each year, sold or not.',
  'Washing-dollar tech founders hire appraisers to value their startups. The appraisers buy boats.',
  ['Billionaire Income Tax Ends a Free Ride on Untaxed Fortunes', 'Taxing Paper Gains Could Force Founders to Sell Their Companies'],
  'Recent federal budget proposals set a 25% minimum tax on income including unrealized gains for households worth over $100 million. Much top wealth is gains never taxed, partly because heirs’ gains are erased at death, but private assets are hard to value.',
  'Taxes the gains that make up most very large fortunes.',
  'Private assets are hard to value, and owners may have to sell shares to pay.',
  'An unrealized gain is the rise in value of something you own but have not sold yet. Today those gains are only taxed when you sell, and the richest families often never sell. This bill taxes them every year for households worth over $100 million. It reaches huge fortunes, but valuing private companies is hard and owners may need to sell to pay.',
  { req: ['~wealth'], slot: ['wealthtax', 'capgains'], sys: ['inctax'] }),
P('cgindex', 'Taxes', 1, [0.1, 0, 0, 0.2, 0, 0], 0.5, null, ['TX', 'FL', 'AZ'], 1,
  'Index capital gains to inflation so only real profits are taxed',
  'The capital gains tax stays after your veto, but the part of a gain that is only inflation is no longer taxed.',
  'Arizona-hot investors learn the difference between real and nominal. Economists weep with joy.',
  ['Another Tax Break for Investors, Dressed Up as Fairness', 'No More Taxing Savers on Phantom Inflation Gains'],
  'Capital gains are taxed on the full rise in price, so part of a long-held asset’s taxable gain can be just inflation. Most of the benefit of indexing would go to high-income households, who earn most capital gains, and it would add complexity.',
  'Fair: nobody should owe tax on a gain that is only inflation.',
  'Mostly helps the wealthy, costs revenue and opens new tax shelters.',
  'A capital gain is the profit when you sell something, like stock, for more than you paid. If prices in general rose over those years, part of that profit is not real. Indexing means only the gain above inflation is taxed. It is fairer to savers, but most of the tax cut goes to wealthy investors.',
  { req: ['~cg0'], slot: ['capgains'], sys: ['inctax'] }),
P('dividendtax', 'Taxes', -1, [-0.1, 0, 0, -0.2, 1, 0], 0.5, ['business', 0.2], ['CT', 'FL', 'NY'], -1,
  'Tax dividends at the same rates as wages',
  'Dividend checks lose their special low rate and are taxed just like a paycheck.',
  'Flori-duh retirees with stock portfolios write strongly worded letters, by mail, with stamps.',
  ['Investors Will Finally Pay the Same Rate as Nurses', 'Double Taxation Gets Worse: Company Profits Hit Twice at Higher Rates'],
  'Since 2003, most dividends have been taxed at the lower capital gains rates. Because company profits are taxed once before being paid out, critics call a higher rate double taxation; supporters say income from work and from owning should be treated alike.',
  'Treats income from owning stocks the same as income from working.',
  'Taxes the same profit twice and may discourage saving and investing.',
  'Dividends are payments companies make to the people who own their stock. Today most are taxed at a lower rate than wages. This bill taxes them like a paycheck. Supporters say that is fair, while critics point out the company already paid tax on those profits, so higher rates could discourage investing.',
  { req: ['!flat'], slot: ['divtax'], sys: ['inctax'] }),
P('flatexempt', 'Taxes', -1, [0, 0, 0, 0.5, 2, 0], 0.5, null, ['MS', 'WV', 'KY'], 2,
  'Add a large family allowance to the new flat tax',
  'After you signed the flat tax, critics noted it hit low earners. Now a big first slice of every family’s income is tax-free.',
  'Kentucky-fried tax code simplified further. The postcard tax return gains exactly one more box.',
  ['Flat Tax Fix Spares Working Families, but the Rich Still Win Most', 'Family Allowance Keeps the Flat Tax Simple and Fair'],
  'The Hall-Rabushka flat tax, the model for most US proposals, includes a large family allowance so low-income households owe nothing. Estonia’s flat income tax also exempts a basic amount. An allowance makes a flat rate somewhat progressive.',
  'Protects low-income families while keeping one simple rate.',
  'Costs revenue, so the single rate may have to rise.',
  'A flat tax charges everyone the same rate. On its own it can raise taxes on low-income families. This bill lets each family earn a large amount before any tax applies, so poorer families owe little or nothing. It keeps filing simple, but the government collects less unless the flat rate goes up.',
  { req: ['flat'], sys: ['inctax'] }),
P('prebate', 'Taxes', -1, [0.1, 0, 0, 1.2, 3, -1], 0.6, null, ['MS', 'AL', 'WV'], 3,
  'Send every household a monthly "prebate" to cover sales tax on necessities',
  'After you replaced the income tax with a consumption tax, families get a monthly check covering the tax on basic spending.',
  'Alabamazing: grandmothers receive monthly checks for buying groceries. Grocery stores approve.',
  ['Prebate Softens a Sales Tax That Hits the Poor Hardest', 'Monthly Checks for Everyone: The Sales Tax Grows a Welfare Program'],
  'The FairTax plan includes a monthly prebate equal to the tax on spending up to the poverty line, so no family pays tax on necessities. Because every household gets it, it would be one of the largest federal programs.',
  'Removes the tax on basic needs, so the poorest pay nothing on essentials.',
  'Very expensive, and the sales tax rate must rise to pay for it.',
  'A national sales tax takes a bigger share of a poor family’s budget, because they spend almost all they earn. A prebate is a monthly check to every household, sized to cover the tax on basic needs like food and clothing. It protects poorer families, but it costs so much that the sales tax rate has to be higher.',
  { req: ['consumptax'] }),
P('vatrebate', 'Taxes', -1, [0, 0, 0, 0.4, 2, 0], 0.5, null, ['NM', 'MS', 'LA'], 2,
  'Pay low-income households a quarterly VAT rebate',
  'With the new 10% VAT on almost everything, lower-income households get a check back every three months.',
  'Louisi-yay-na families get a check that covers the tax on their gumbo ingredients.',
  ['VAT Rebate Shields Working Families From a Regressive Tax', 'Tax Everyone, Then Mail It Back: Washington Invents a Round Trip'],
  'Most countries with a VAT soften its burden on the poor with lower rates on food. Canada instead pays a quarterly GST/HST credit to lower-income households, which keeps one rate for nearly everything.',
  'Protects lower-income families while keeping the VAT simple.',
  'Gives back part of the revenue the VAT was meant to raise.',
  'A value-added tax, or VAT, is a tax on almost everything people buy. Poorer families feel it more because they spend most of their income. This bill sends them a check four times a year to offset it. It keeps the VAT simple and fairer, but returns some of the money it was supposed to raise.',
  { req: ['natvat'] }),
P('irsup', 'Taxes', -1, [0, 0, 0, -0.3, -1, 0], 0.6, ['business', 0.15], ['NV', 'TX', 'WY'], -1,
  'Boost IRS funding for audits of high earners and big companies',
  'More auditors, better computers, and a promise that waiters will not be the target.',
  'The IRS hires agents. Wyo-mingle ranchers stock up on filing cabinets just in case.',
  ['Tax Cheats on Notice as IRS Gets Resources to Collect What Is Owed', 'An Army of Auditors Is Coming, and It Won’t Stop at the Rich'],
  'The 2022 Inflation Reduction Act gave the IRS about $80 billion, though Congress later cut part of it. CBO has estimated that added enforcement money raises more revenue than it costs, especially for audits of high earners.',
  'Collects taxes already owed, cutting the deficit without raising rates.',
  'More audits burden honest taxpayers, and the agency may overreach.',
  'The IRS is the agency that collects federal taxes. Some people and companies pay less than they owe, and catching them takes trained auditors. This bill gives the IRS more money to check returns from high earners and big firms. Studies say it brings in more revenue than it costs, but many people distrust the IRS and fear more audits.',
  { slot: ['irs'] }),
P('irsdown', 'Taxes', 2, [0, 0, 0, 0.2, 1, 0], 0.5, null, ['WY', 'TX', 'FL'], 1,
  'Cut the IRS budget by a fifth',
  'Fewer auditors, fewer letters, fewer people answering the phones. The tax code stays the same size.',
  'Taxpayers celebrate, then wait on hold for three hours to ask a simple question.',
  ['IRS Cuts Are a Gift to Tax Cheats, Paid for by Everyone Else', 'Shrinking the Taxman: Fewer Agents Means Fewer Harassed Families'],
  'CBO has estimated that cutting IRS enforcement funding raises deficits, because lost revenue exceeds the savings. Phone service and refund delays have tended to worsen when IRS staffing falls.',
  'Shrinks an agency many people distrust and trims federal spending.',
  'Tax cheats pay less, honest taxpayers get worse service, and deficits rise.',
  'The IRS collects federal taxes and checks that people pay what they owe. Cutting its budget saves some spending and means fewer audits, which many people like. But with fewer agents, more taxes go unpaid, so by CBO’s estimate the government loses more money than it saves, and help lines get slower.',
  { slot: ['irs'] }),
P('taxfiling', 'Taxes', -1, [0, 0, 0, 0.05, 2, 0], 0.5, ['business', 0.15], ['CA', 'NY', 'AZ'], 2,
  'Let every taxpayer file free online directly with the IRS',
  'With the IRS newly funded, it runs its own free filing website. Tax-prep companies lose their favorite season.',
  'Arizona taxpayers file in 40 minutes. Tax software ads pivot to selling peace of mind.',
  ['Free Filing Ends the Tax-Prep Toll Booth', 'The Tax Collector Becomes Your Tax Advisor. What Could Go Wrong?'],
  'The IRS Direct File pilot let taxpayers in 12 states file free in 2024 and expanded to more states in 2025. Commercial tax-prep firms have long lobbied against government filing tools.',
  'Saves families money and time on a task the government requires.',
  'The IRS would be both the tax collector and the helper filling out the form.',
  'Every year Americans must file a tax return, and many pay a company to help. This bill lets anyone file for free on an IRS website. Families save money and time, but tax-prep companies lose business, and some worry about the IRS helping people fill out forms it also checks.',
  { req: ['irsup'], sys: ['inctax'] }),
P('prefill', 'Taxes', -1, [0, 0, 0, 0.05, 2, 0], 0.5, ['business', 0.15], ['CA', 'NY', 'IL'], 2,
  'Send simple filers a pre-filled tax return to check and sign',
  'The free IRS site already knows your wages. Now it fills in the return and you just confirm it.',
  'Illinoisy tax season goes quiet. Families sign a form in five minutes and go back to bed.',
  ['Taxes in Five Minutes: Pre-Filled Returns Finally Arrive', 'The IRS Now Tells You What You Owe. Check Its Math.'],
  'Countries such as Sweden and Estonia send many taxpayers pre-filled returns to confirm. The IRS already receives most wage, interest and dividend data from employers and banks, so for simple returns it knows most of the numbers.',
  'Saves time and money, and catches mistakes before they happen.',
  'Taxpayers may accept the IRS’s numbers without checking, even when they are wrong.',
  'Employers and banks already report your wages and interest to the IRS. With pre-filled returns, the IRS puts those numbers on a form and sends it to people with simple taxes, who just check it and sign. It saves a lot of time, but people might not notice mistakes or credits they are owed.',
  { req: ['taxfiling'], sys: ['inctax'] }),
P('windrebate', 'Taxes', -1, [0.05, 0, 0.1, 0.5, 3, -1], 0.5, null, ['ME', 'MI', 'PA'], 2,
  'Send windfall-tax revenue back to households as energy rebate checks',
  'The oil windfall tax is being collected; now families get it back as checks for heating and gas bills.',
  'Maine-ly grateful: heating oil customers receive checks. Oil executives receive a postcard.',
  ['Oil Profits Return to the Families Who Paid at the Pump', 'Rebate Checks Pour Fuel on Inflation Just as Prices Spike'],
  'When Britain added an Energy Profits Levy on oil and gas producers in 2022, it paired it with help for household energy bills. Rebate checks ease budgets but can slightly add to demand when energy is scarce.',
  'Returns the extra profits to the families squeezed by high prices.',
  'Spends the revenue instead of cutting debt and can keep demand and prices high.',
  'A windfall tax takes a share of the extra profits oil companies earn when prices jump. This bill sends that money to families as rebate checks to help pay energy bills. It helps households hit by high prices, but the money is spent instead of lowering the deficit, and extra spending can push prices up a little.',
  { req: ['windfall'] }),
P('estate', 'Taxes', 2, [0.05, 0, 0, 0.2, -1, 0], 0.5, null, ['IA', 'NE', 'KS'], 1,
  'Repeal the federal estate tax',
  'Inheritances of any size pass to heirs with no federal estate tax, family farms and billionaires alike.',
  'Iowa farm families relax. Iowa estate lawyers check the job listings in Delaware.',
  ['Estate Tax Repeal Hands Billionaire Heirs a Fortune', 'Death Tax Buried at Last: Family Farms No Longer Sold to Pay the IRS'],
  'Because each person can pass on more than $13 million tax-free, well under 1 percent of estates owe federal estate tax, and very few of those are farms. It raises a small share of federal revenue.',
  'Lets families pass on farms and businesses without a tax bill at death.',
  'Helps only the largest estates and lets big fortunes pass on untaxed.',
  'The estate tax is charged on what very wealthy people leave behind when they die. Today only the biggest estates owe anything. Repealing it means heirs keep everything. Supporters say it protects family businesses and farms; critics say it mainly helps the richest families and loses revenue.',
  { slot: ['estate'] }),
P('minimumtax', 'Taxes', -1, [-0.1, 0, 0, -0.2, 1, 0], 0.6, ['business', 0.3], ['DE', 'NY', 'CA'], -1,
  'Extend the 15% corporate minimum tax to firms with $100 million in profits',
  'Companies that report big profits to shareholders but little to the IRS must pay at least 15%. Now firms with $100 million in profits count too.',
  'Accountants reconcile two sets of books, legally. Delaware holds a moment of silence.',
  ['More Profitable Corporations Pay Their Fair Share', 'Minimum Tax Expansion Buries More Firms in Paperwork'],
  'The 2022 Inflation Reduction Act created a 15% minimum tax on the profits that corporations reporting over $1 billion show to investors. It targets firms that report large profits but pay little tax because of deductions and credits.',
  'Stops profitable companies from paying almost nothing in tax.',
  'Ties tax to accounting rules written for investors and adds complex paperwork.',
  'Companies keep two sets of numbers: profits they report to investors and profits they report for taxes. Thanks to deductions, some report big profits but pay little tax. A minimum tax says they must pay at least 15% of their reported profit. This bill extends it to firms with $100 million in profits, raising revenue but adding paperwork.',
  { slot: ['camt'], sys: ['corp'] }),
P('rdcredit', 'Taxes', 1, [0.15, -0.05, 0, 0.2, 1, 0], 0.6, null, ['CA', 'WA', 'MA'], 1,
  'Double the research and development tax credit',
  'Companies that pay for research get twice the tax credit for it. Labs everywhere order another whiteboard.',
  'Massachu-sets of beakers ordered. Accounting departments wonder if the copier counts as research.',
  ['Another Corporate Tax Break, This Time Wearing a Lab Coat', 'Tax Credit for Inventors Keeps America Ahead in the Tech Race'],
  'The federal research credit dates to 1981 and was made permanent in 2015. Economists widely find research benefits others beyond the firm paying for it, which justifies support, but firms may relabel routine work as research.',
  'Encourages research whose benefits spread across the whole economy.',
  'Costs revenue and partly rewards research firms would do anyway.',
  'A tax credit lowers a company’s tax bill dollar for dollar. This one rewards spending on research, like new medicines or computer chips. Research often helps the whole economy, not just the company paying for it, so supporters want more of it. Critics say it costs money and some companies call ordinary work research.',
  { slot: ['rdcredit'], sys: ['corp', 'deduct'] }),
// ------------------------------------------------------------------ WELFARE
P('eitc', 'Welfare', -1, [0.05, -0.1, 0, 0.3, 2, 0], 0.6, null, ['MS', 'LA', 'AL'], 2,
  'Expand the Earned Income Tax Credit by 20%',
  'Working families with low pay get a bigger refund at tax time. Earn more, up to a point, and the credit grows.',
  'Missi-sippi working parents get bigger refunds. Mattress stores note a suspicious spring rush.',
  ['Bigger EITC Rewards Work and Lifts Families Out of Poverty', 'EITC Grows, and So Does Its Error Rate'],
  'The EITC is one of the largest anti-poverty programs for working families, and studies of the 1990s expansions found it drew many single mothers into work. The IRS estimates a large share of its payments are made in error.',
  'Rewards work and lifts working families out of poverty.',
  'Costs money, and errors and fraud are a persistent problem.',
  'The Earned Income Tax Credit gives money back at tax time to people who work but earn little. You only get it if you have earnings, so it encourages work. Making it 20% bigger helps millions of working families, but it costs money and many payments go to people who do not qualify by mistake.',
  { slot: ['eitc'], sys: ['inctax', 'deduct'] }),
P('eitcless', 'Welfare', -1, [0, -0.05, 0, 0.2, 1, 0], 0.5, null, ['MS', 'WV', 'NM'], 1,
  'Triple the EITC for workers without children',
  'After the family EITC grew, single low-wage workers ask for their share. Their credit today is tiny.',
  'Newer Mexico line cooks with no kids get a credit bigger than a pizza, for once.',
  ['Childless Workers, Long Left Out, Finally Get a Real Credit', 'EITC Expansion Spreads Costs to a Group It Was Never Built For'],
  'Workers without children get a very small EITC, available only from age 25 to 64. A temporary 2021 expansion roughly tripled it, and a New York City pilot paying a larger credit found modest gains in work and earnings for some groups.',
  'Pulls more low-wage adults into work and helps them stay there.',
  'Adds cost, and evidence of large effects on work is limited.',
  'The Earned Income Tax Credit mostly helps parents. Workers without kids get only a few hundred dollars at most. This bill triples that amount for low-wage single workers. It may encourage more people to work and lowers poverty, but it adds cost and the evidence that it boosts work much is mixed.',
  { req: ['eitc'], sys: ['inctax', 'deduct'] }),
P('eitcyoung', 'Welfare', -1, [0, -0.05, 0, 0.1, 1, 0], 0.4, null, ['MS', 'GA', 'NM'], 1,
  'Open the childless EITC to working adults aged 19 to 24',
  'The bigger childless credit only starts at 25. Now young workers who are not full-time students qualify too.',
  'Georgia-ous news for 20-year-old warehouse workers: a tax refund that is not a typo.',
  ['Young Workers Get a Leg Up as the EITC Age Limit Drops', 'Washington Expands Tax Credits to Young Adults Still at Home'],
  'The 2021 relief law lowered the minimum age for the childless EITC for one year, generally to 19, with exceptions for full-time students. Research finds early work experience is linked to higher earnings later in life.',
  'Helps young adults build work habits and income early in life.',
  'Some recipients are supported by their parents, and costs rise.',
  'Right now, workers without children cannot get the Earned Income Tax Credit until age 25. This bill lets low-paid workers aged 19 to 24 who are not full-time students qualify. It rewards young people for working and may help them build careers, but it costs more and some of them already get help from parents.',
  { req: ['eitcless'], sys: ['inctax', 'deduct'] }),
P('ctc', 'Welfare', -2, [0.05, 0.05, 0.1, 1.0, 3, 0], 0.7, null, ['WV', 'MS', 'NM'], 3,
  'Raise the child tax credit to up to $3,600 and pay it in full to the poorest families',
  'Every child brings a bigger credit, and families who earn too little to owe income tax get the whole amount.',
  'Wild, Wonderful West Virginia families buy winter coats in October instead of January.',
  ['Child Poverty Plunges as Families Get a Real Credit', 'Credit With No Work Link Could Pull Parents Out of Jobs'],
  'The 2021 relief law raised the credit to $3,000 to $3,600 per child and made it fully refundable for one year. Census data show child poverty under its supplemental measure fell to a record low in 2021 and more than doubled in 2022 after it ended.',
  'Cuts child poverty sharply and helps with the real cost of raising kids.',
  'Very expensive, and cutting the link to work may lead some parents to work less.',
  'The child tax credit lowers taxes for families with kids. Today the poorest families get only part of it because they earn too little to owe much tax. This bill makes it bigger and gives the full amount to everyone, even with no income. Child poverty would fall a lot, but it is expensive and some worry parents might work less.',
  { slot: ['ctc'], sys: ['inctax', 'deduct'] }),
P('ctcmonth', 'Welfare', -1, [0, 0, 0, 0.05, 2, 0], 0.5, null, ['WV', 'OH', 'MS'], 2,
  'Pay the child tax credit in monthly installments',
  'The bigger child credit now arrives every month instead of once a year at tax time. Rent is due monthly too.',
  'Ohi-yo! Parents get a deposit on the 15th. Grocery stores notice a pattern.',
  ['Monthly Child Payments Help Families Keep Up With Bills', 'Advance Checks Mean Overpayments the IRS Must Claw Back Later'],
  'In the second half of 2021 the IRS sent monthly child credit payments to tens of millions of families. Surveys found families mostly spent them on food, bills and school costs; some later owed money back when their income or custody changed.',
  'Matches help to monthly bills, so families avoid debt between tax seasons.',
  'Advance payments based on old data can lead to surprise repayments.',
  'Normally the child tax credit comes once a year when families file taxes. This bill splits it into monthly payments, so families get help when bills are due. It makes budgeting easier, but the IRS must guess each family’s situation in advance, and some families may have to pay money back later.',
  { req: ['ctc'], sys: ['inctax', 'deduct'] }),
P('ctcwork', 'Welfare', 1, [0, -0.05, 0, -0.3, -1, 0], 0.5, null, ['WV', 'MS', 'NM'], -1,
  'Require some earnings to receive the full monthly child credit',
  'Monthly child payments continue, but the full amount now phases in as parents earn income.',
  'Wild, Wonderful West Virginia parents read the fine print. The fine print asks for a pay stub.',
  ['Work Rule Cuts Off Help to the Poorest Children', 'Child Credit Rewards Work Again, as It Did for Decades'],
  'Before 2021, the credit phased in with earnings, so the poorest families got little or none. Economists disagree on how many parents would leave work without that link; estimates range from almost no one to over a million.',
  'Keeps the credit tied to work and lowers its cost.',
  'The poorest children, whose parents earn least, get the least help.',
  'This bill keeps the monthly child payments but says parents must earn some income to get the full amount. Supporters say help should reward work and it saves money. Opponents point out that children in the poorest homes, who need help most, would get less, and studies disagree on how much it changes work.',
  { req: ['ctcmonth'], sys: ['inctax', 'deduct'] }),
// ------------------------------------------------------------------ RETIREMENT
P('autoira', 'Retirement', -1, [0, 0, 0, 0.05, 2, 0], 0.5, ['business', 0.1], ['CA', 'OR', 'IL'], 1,
  'Automatically enroll workers with no job retirement plan in an IRA',
  'If your employer offers no 401(k), a slice of each paycheck goes into a retirement account unless you opt out.',
  'Oregon-ized savings: millions of workers discover they own retirement accounts. Most keep them.',
  ['Auto-IRA Gives Every Worker a Shot at a Secure Retirement', 'Another Mandate on Small Business, This Time With a Payroll Form'],
  'Tens of millions of private-sector workers have no retirement plan at work. Studies find automatic enrollment sharply raises participation, and state programs such as OregonSaves and CalSavers already work this way.',
  'Helps millions start saving for retirement with almost no effort.',
  'Adds paperwork for small employers, and small balances may be cashed out early.',
  'Many workers have no retirement savings plan at their job. This bill makes employers without one send a small part of each paycheck into a retirement account for the worker, who can opt out. People tend to stick with the default, so saving jumps. It adds paperwork for small businesses, and some savers cash out early.',
  { slot: ['autoira'], sys: ['inctax'] }),
P('ssfix', 'Retirement', 0, [-0.1, 0, 0, -0.4, -1, 0], 0.6, ['retirees', 0.1], ['FL', 'AZ', 'PA'], -1,
  'Pass a bipartisan Social Security rescue: higher wage cap, slower benefit growth at the top',
  'After the big Social Security fights, a middle path: high earners pay more and get slightly smaller raises.',
  'Flori-duh retirees read the plan twice and decide they can live with it. Mostly.',
  ['Social Security Deal Protects Benefits but Trims Them for the Well-Off', 'Bipartisan Deal Raises Taxes on Workers to Prop Up a Shaky System'],
  'The trustees project the retirement trust fund can pay full benefits only until the mid-2030s, then roughly 80 percent. The 1983 rescue, which raised payroll taxes and slowly raised the retirement age, is the model for bipartisan deals.',
  'Keeps Social Security solvent for decades through shared sacrifice.',
  'Raises taxes and trims benefits, so few voters love it.',
  'Social Security is running short of money because there are more retirees per worker. Without changes, checks will be cut in the 2030s. This deal makes high earners pay tax on more of their wages and slows benefit growth for the best-off retirees. It keeps the program paying, but everyone gives something up.',
  { req: [['~ssx', '~ssp']], slot: ['ssbenefit', 'payrollcap'] }),
P('sstrust', 'Retirement', -1, [0, 0, 0, 0.9, 3, 0], 0.6, null, ['FL', 'AZ', 'PA'], 3,
  'Top up the Social Security trust fund from general tax revenue',
  'You vetoed the Social Security deal. With the trust fund running down, Congress proposes covering the gap from regular taxes.',
  'Flori-duh shuffleboard leagues cheer. Deficit hawks circle overhead, as usual.',
  ['Seniors Protected From Automatic Benefit Cuts', 'Bailout Breaks the Promise That Social Security Pays for Itself'],
  'Social Security has been funded almost entirely by its own payroll taxes and their interest. Without changes, benefits face an automatic cut of about a fifth in the mid-2030s, because the program may only pay out what its trust funds hold.',
  'Prevents a sudden benefit cut for tens of millions of retirees.',
  'Adds to the national debt and removes pressure for a lasting fix.',
  'Social Security is paid for by a special tax on paychecks. That money is running short, and when the trust fund runs out, checks would be cut automatically. This bill fills the gap with money from the regular federal budget. Retirees are protected, but the national debt grows and the real problem is put off.',
  { req: ['~ssfix'] }),
// ------------------------------------------------------------------ BUDGET
P('balbud', 'Budget', 2, [-0.3, 0.2, -0.1, -1.0, -1, 1], 0.6, ['labor', 0.2], ['VA', 'MD', 'NM'], -2,
  'Require a balanced budget within ten years, enforced by automatic cuts',
  'After the fight over across-the-board cuts, a slower plan: yearly deficit targets, and automatic trims if Congress misses them.',
  'Marylandslide of federal contractors updating their resumes. Budget hawks finally sleep at night.',
  ['Automatic Cuts Put Food Aid and Schools on the Chopping Block', 'Washington Finally Forced to Live Within Its Means'],
  'The 1985 Gramm-Rudman-Hollings law set deficit targets backed by automatic cuts; Congress repeatedly moved the targets and in 1990 replaced them with pay-as-you-go rules. Most states have balanced-budget rules, but they can borrow for buildings and roads.',
  'Forces hard choices now instead of passing debt to the next generation.',
  'Automatic cuts during a recession can make the downturn worse.',
  'The government spends more than it collects, and borrows the rest, which adds to the national debt. This law sets yearly targets to close that gap within ten years. If Congress misses a target, spending is cut automatically. It forces discipline, but automatic cuts can hit useful programs and hurt during a recession.',
  { req: [['cut10', '~cut10']], slot: ['balbud'] }),
P('imprec', 'Budget', 1, [-0.05, 0, 0, -0.2, 0, 0], 0.5, null, ['VA', 'MD', 'AK'], -1,
  'Fast-track votes on the President’s proposed spending cancellations',
  'To hit the balanced-budget target, the President may send Congress a list of spending to cancel, and Congress must vote quickly.',
  'Alaskan bridge-to-somewhere projects nervously check the list. The list is long.',
  ['Fast-Track Cuts Hand the White House Power Over Congress’s Purse', 'A Scalpel for Wasteful Spending, at Last'],
  'Congress passed a line-item veto in 1996, but the Supreme Court struck it down in 1998. Expedited rescission plans try to get similar results legally, by forcing quick up-or-down votes on the president’s proposed cuts.',
  'Makes it easier to cut wasteful items buried in giant spending bills.',
  'Shifts budget power toward the President and invites political targeting.',
  'Huge spending bills often hide small projects few people would vote for alone. This law lets the President send Congress a list of items to cancel, and Congress must vote yes or no quickly. It helps meet budget targets, but gives the President more power over spending, which could be used to punish opponents.',
  { req: ['balbud'] }),
P('defcut', 'Budget', 0, [-0.1, 0.1, 0, -0.3, 0, 0], 0.5, null, ['VA', 'CA', 'AL'], -2,
  'Cut the defense budget by 10%',
  'The Pentagon trims ships, bases and contracts. The generals are asked to pick which ones.',
  'Virginia defense contractors rehearse sad slide decks. The Pentagon finds three spare warehouses.',
  ['Defense Cut Frees Billions for Needs at Home', 'Military Cuts Invite Trouble in a Dangerous World'],
  'US military spending is roughly 3 percent of GDP, more than the next several countries combined. Spending is concentrated near bases and shipyards, so cuts hit states like Virginia and California hardest.',
  'Saves money in the biggest yearly budget item, at an agency that has never passed a full audit.',
  'May weaken deterrence and costs jobs in defense towns.',
  'Defense is the largest part of the budget that Congress votes on each year. This bill cuts it by a tenth. Supporters say the Pentagon wastes money and the savings could pay for other things or lower the deficit. Opponents worry about weaker defenses and lost jobs at bases and factories.',
  { slot: ['defense'] }),
P('defup', 'Budget', 0, [0.2, -0.1, 0.1, 1.0, 1, 0], 0.6, null, ['VA', 'TX', 'AL'], 2,
  'Raise defense spending to 4% of GDP',
  'More ships, drones and missile defense. Shipyards hire, and so does the deficit.',
  'Alabama rocket engineers get raises. Texas bases repaint the welcome signs.',
  ['Pentagon Gets Billions More While Schools Wait', 'Stronger Military Keeps Rivals in Check'],
  'US defense spending fell from about 6 percent of GDP in the mid-1980s to around 3 percent today. NATO members agreed in 2025 to aim for 5 percent of GDP on defense and related spending by 2035.',
  'Deters rivals and keeps the military ahead in new technology.',
  'Adds to the deficit, and more money does not guarantee better forces.',
  'GDP is the total value of everything the country produces. This bill raises military spending to 4 cents of every dollar of it, up from about 3. Supporters say a stronger military keeps rivals from starting wars. Critics say it adds to the deficit and that the Pentagon should spend its current money better first.',
  { slot: ['defense'] }),
// ------------------------------------------------------------------ FINANCE
P('capreq', 'Finance', -1, [-0.1, 0, 0, 0, 1, 0], 0.6, ['business', 0.25], ['NY', 'NC'], -1,
  'Make big banks fund more of their lending with their own capital',
  'Big banks must hold more shareholder money as a cushion, so losses hit owners before taxpayers.',
  'Newer York bankers practice saying "safer" without wincing. Charlotte banks hire more spreadsheet artists.',
  ['Stronger Cushions Mean Taxpayers Won’t Bail Out Banks Again', 'Capital Rules Will Squeeze Lending to Families and Small Firms'],
  'After 2008, regulators required banks to fund more of their lending with shareholders’ money rather than borrowing. A 2023 proposal to raise requirements further was scaled back after heavy industry pushback.',
  'Makes bank failures and taxpayer bailouts less likely.',
  'May raise borrowing costs and push lending to less regulated firms.',
  'Banks lend out money they mostly borrow from depositors. Capital is the owners’ own money, which absorbs losses first if loans go bad. This rule makes big banks keep more of it. That makes failures and bailouts less likely, but banks say it will make loans a little more expensive and scarcer.',
  { slot: ['bankreg'] }),
P('dodd', 'Finance', 2, [0.1, 0, 0, 0, -1, 0], 0.5, null, ['NC', 'UT', 'SD'], 1,
  'Roll back Dodd-Frank rules for regional banks',
  'Mid-sized banks get lighter stress tests and less paperwork, and promise to lend more.',
  'Utah-mazing: community bankers celebrate with a sensible lunch. Regulators keep the receipts.',
  ['Regulators Asleep Again: Lessons of Bank Failures Forgotten', 'Relief for Main Street Banks Buried Under Big-Bank Rules'],
  'A 2018 law raised the size at which banks face the strictest Dodd-Frank oversight from $50 billion to $250 billion in assets. Some critics linked lighter oversight to the 2023 failure of Silicon Valley Bank; others blamed bank managers and supervisors.',
  'Cuts costs for mid-sized banks so they can lend more to local businesses.',
  'Raises the risk of bank failures like those in 2023.',
  'After the 2008 financial crisis, the Dodd-Frank law added strict checks on banks, such as stress tests that ask whether a bank could survive a crash. This bill eases those rules for mid-sized regional banks. They save money and may lend more, but lighter oversight can let problems grow until a bank fails.',
  { slot: ['bankreg'] }),
P('fdic', 'Finance', -1, [0.05, 0, 0.05, 0, 1, 0], 0.5, ['business', 0.1], ['CA', 'MA', 'NY'], 1,
  'Fully insure business payment accounts at banks',
  'Companies can keep payroll money in a bank without fearing a run. Banks pay higher insurance fees to cover it.',
  'California startups stop keeping their payroll in seven different banks. Treasurers sleep again.',
  ['Deposit Insurance Fix Stops Bank Runs Before They Start', 'Bigger Guarantees Invite Banks to Take Bigger Risks'],
  'FDIC insurance covers $250,000 per depositor per bank. In 2023 regulators protected all deposits at Silicon Valley Bank and Signature Bank to stop a panic, raising the question of where the line should be.',
  'Prevents bank runs and keeps small firms’ payrolls safe.',
  'Encourages risk-taking, and the fees may be passed on to customers.',
  'The FDIC is a government agency that guarantees bank deposits up to $250,000, paid for by fees on banks. Businesses often keep far more than that to pay workers, so a scare can cause a run. This bill fully insures those payment accounts. Runs become less likely, but banks and depositors may take more risks.',
  { slot: ['fdic'] }),
P('cfpb', 'Finance', 2, [0.05, 0, 0, -0.02, -2, 0], 0.5, ['urban', 0.15], ['NY', 'CA', 'IL'], -2,
  'Shut down the Consumer Financial Protection Bureau',
  'The consumer finance watchdog closes; some of its rules move to bank regulators and the rest lapse.',
  'Illinoisy consumer groups protest. Bank compliance departments quietly update their binders.',
  ['Watchdog Killed: Families Lose Their Defender Against Financial Tricks', 'Unaccountable Agency Closed After Years of Overreach'],
  'The CFPB was created by the 2010 Dodd-Frank Act and reports billions of dollars in relief to consumers. Critics object that its funding bypasses yearly votes in Congress; the Supreme Court upheld that funding setup in 2024.',
  'Ends an agency critics say overreaches and raises costs for lenders.',
  'Leaves consumers with less protection from unfair loans and fees.',
  'The Consumer Financial Protection Bureau writes and enforces rules for mortgages, credit cards and other loans to protect regular people. This bill closes it. Supporters say it is too powerful and makes credit more costly. Opponents say families would be more exposed to hidden fees and unfair lending.',
  { slot: ['cfpb'] }),
P('payday', 'Finance', -1, [-0.05, 0, 0, 0, 2, 0], 0.5, ['business', 0.15], ['TX', 'OH', 'MS'], 1,
  'Cap payday and small-loan interest rates at 36% a year',
  'Credit-card rates had their fight; now far pricier payday loans face a limit of 36% a year.',
  'Texas-sized payday loan signs come down. Pawn shops redecorate.',
  ['Loan Sharks Lose Their Teeth With 36% Rate Cap', 'Rate Cap Leaves Struggling Borrowers With Nowhere Left to Turn'],
  'Federal law already caps loans to active-duty troops at 36% a year, and many states cap payday loans similarly. Studies find caps nearly end storefront payday lending, with mixed evidence on whether borrowers end up better off.',
  'Stops two-week loans whose fees work out to rates near 400% a year.',
  'People with poor credit may lose access to emergency cash.',
  'Payday loans are small, short loans meant to last until the next paycheck. Their fees are so high that, counted over a year, the interest rate can reach hundreds of percent. This bill caps it at 36%. Borrowers are protected from debt traps, but many lenders would close, leaving some people with no quick way to borrow.',
  { req: [['ccap', '~ccap']], slot: ['payday'] }),
P('bnplcap', 'Finance', -1, [-0.05, 0, 0, 0, 1, 0], 0.5, ['business', 0.1], ['CA', 'NY', 'GA'], 1,
  'Apply credit-card protections to buy-now-pay-later loans',
  'With card rates capped, shoppers and lenders are drifting to pay-in-four plans. Now those get the same dispute rights.',
  'Georgia shoppers can now dispute the sneakers they split into four payments.',
  ['Pay-Later Loans Finally Covered by Consumer Protections', 'Regulators Smother the Interest-Free Loans Shoppers Love'],
  'Buy-now-pay-later loans split purchases into a few payments, often interest-free, and grew rapidly in the 2020s. A 2024 federal interpretation treating them like credit cards was withdrawn in 2025. Users can stack several loans that lenders may not see.',
  'Gives shoppers refund and dispute rights and limits hidden fees.',
  'Raises costs for a product many people use responsibly.',
  'Buy-now-pay-later lets shoppers split a purchase into a few payments, often with no interest. With card rates capped, more shoppers may turn to it. But it lacks some protections credit cards have, like disputing a charge. This bill adds them. Shoppers are safer, but the plans may cost more to offer.',
  { req: ['ccap'] }),
P('postbank', 'Finance', -2, [0, 0, 0, 0.05, 2, 0], 0.6, ['business', 0.15], ['MS', 'AL', 'NM'], 2,
  'Let the Post Office offer basic banking and small loans',
  'Cash checks, pay bills and borrow small sums at the post office counter, with low fees. The line for stamps gets longer.',
  'Alabamazing: the post office now cashes checks. The stamp line and the loan line are the same line.',
  ['Postal Banking Brings Fair Finance to Neighborhoods Banks Abandoned', 'Struggling Post Office Wants to Be a Bank Now'],
  'The Post Office ran a savings system from 1911 to 1967. The FDIC finds roughly 4 to 5 percent of US households have no bank account; critics doubt the Postal Service could run lending well or profitably.',
  'Brings low-cost banking to people far from a bank branch.',
  'The Post Office lacks banking experience and could lose money.',
  'Some Americans have no bank account and pay high fees to cash checks or borrow. Post offices are in almost every town. This bill lets them offer simple banking and small loans at low cost. It could help people banks ignore, but the Post Office has little experience with loans and could lose money.',
  { req: ['!postsell', ['payday', '~payday']], sys: ['postal'] }),
P('crypto', 'Finance', 1, [0.05, 0, 0, 0, -1, 0], 0.5, null, ['WY', 'TX', 'FL'], 1,
  'Set clear federal rules for crypto trading platforms',
  'Crypto exchanges register with one regulator, keep customer money separate, and finally learn who is in charge.',
  'Wyo-mingle crypto miners celebrate with a cake shaped like a hardware wallet.',
  ['Crypto Bill Gives a Scandal-Prone Industry Light Rules', 'Clear Rules at Last Keep Crypto Innovation in America'],
  'A 2025 law set federal rules for dollar-backed stablecoins, but trading platforms for other tokens still face disputes between the SEC and CFTC over who oversees them. The 2022 collapse of FTX left customers with billions in frozen funds.',
  'Protects customers and keeps crypto businesses from moving abroad.',
  'May give a risky industry an official stamp of approval.',
  'Cryptocurrencies like bitcoin are digital money traded on online exchanges. Two US agencies argue over who should oversee them, and some exchanges have collapsed with customers’ money. This bill picks clear rules and one regulator. Customers get more protection, but critics say it makes a risky industry look safer than it is.',
  { slot: ['crypto'] }),
P('creditscore', 'Finance', -1, [-0.05, 0, 0, 0, 2, 0], 0.5, ['business', 0.1], ['MS', 'TX', 'WV'], 1,
  'Ban medical debt from credit reports',
  'An unpaid hospital bill can no longer drag down your credit score.',
  'Texas-sized ER bills stop following patients to the car dealership.',
  ['Getting Sick Will No Longer Wreck Your Credit', 'Hiding Debts From Lenders Could Raise Rates for Everyone'],
  'The three big credit bureaus stopped reporting paid medical debt and medical debts under $500 in 2022 and 2023. A broader 2025 federal rule removing the rest was struck down in court. Research finds medical debt predicts repayment less well than other debts.',
  'Medical debt often reflects billing chaos, not whether someone repays loans.',
  'Lenders lose information, and some patients may stop paying their bills.',
  'A credit score tells lenders how likely you are to repay a loan. Unpaid medical bills can lower it, even when the bill was confusing or wrong. This bill keeps medical debt off credit reports. People who got sick can borrow more easily, but lenders see less information and hospitals may collect less.',
  { slot: ['creditscore'] }),
];
