import { createRequire } from 'node:module';
const require = createRequire('/opt/npm-tools/node_modules/');
const { chromium } = require('playwright');
const OUT = process.env.SHOTS || '/tmp/claude-0/-home-claude/c5c287cf-83a5-5f1d-b586-c681fd0fd053/scratchpad/v2shots';
const URL = process.env.URL || 'http://localhost:4173/';
const which = process.argv[2] || 'desktop';
const b = await chromium.launch();
const ctx = await b.newContext(which === 'phone' ? { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true } : { viewport: { width: 1280, height: 800 } });
const p = await ctx.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push('pageerror ' + e.message));
p.on('console', (m) => { if (m.type() === 'error' && !/fonts|ERR_|supabase|Failed to load resource/.test(m.text())) errs.push('console ' + m.text()); });
await p.route(/fonts\.(googleapis|gstatic)\.com/, (r) => r.abort());
await p.goto(URL); await p.waitForTimeout(600);
const shot = async (n) => { await p.waitForTimeout(500); await p.screenshot({ path: `${OUT}/${which}-${n}.png` }); };
await shot('01-title');
await p.evaluate(() => { window.__app.noDelay = true; });
await p.getByRole('button', { name: /Begin Day 1/ }).click(); await shot('02-map-tutorial');
await p.getByRole('button', { name: /Go to my Desk/ }).click(); await shot('03-desk-memo');
await p.getByRole('button', { name: /Next/ }).click(); await shot('04-desk-exec-open');
// pick an exec action
await p.locator('.xrow').first().click(); await shot('05-exec-detail');
await p.getByRole('button', { name: /^Back$/ }).click();
await p.getByRole('button', { name: /Next/ }).click(); await shot('06-press-tutorial');
await p.getByRole('button', { name: /Got it/ }).click();
// memos
await p.getByRole('button', { name: /Sign it/ }).click(); await p.waitForTimeout(300);
await p.getByRole('button', { name: /^Veto$/ }).click(); await p.waitForTimeout(300);
await p.getByRole('button', { name: /Sign it/ }).click(); await p.waitForTimeout(300);
await shot('07-memos-done');
await p.getByRole('button', { name: /End the day/ }).click(); await shot('08-after-endday');
console.log('phase', await p.evaluate(() => window.__app.state.g.phase));
await p.getByRole('button', { name: 'Press', exact: true }).click().catch(() => {}); await shot('09-press');
await p.getByRole('button', { name: 'Map', exact: true }).click().catch(() => {}); await shot('10-map');
console.log('errors:', errs.length ? errs.join('\n') : 'none');
await b.close();
